### ISSUE TITLE
Improve application context detection

### ISSUE THREAD

**Issue by chilimangoes** [dictation-toolbox/Caster#106]
Dragonfly's built-in AppContext waits until the user starts speaking to detect application context changes. I would like to take a shot at detecting application switches using the native Windows API. Using this method, we could eliminate some of the window polling that Caster currently does, and potentially improve performance.

Additionally, as I've had to work from home the last couple of days and connect to my work computer over the VPN, I'm noticing that it would be nice to have application-specific grammars work correctly over an RDP session. This may be easier said than done with firewalls and such getting in the way, but again it's something I'd like to try.

**Comment by synkarius** [comment]
These sound awesome. I'm very interested in the first one in particular.

**Comment by chilimangoes** [comment]
Had another thought about this earlier today. In addition to providing information about which app has focus, our context provider could serve as a repository for other useful information. For example, which monitor the active application is on, what the coordinates and window size of the app's main window are, client rectangle of the currently focused control/window within the application, whether the start menu is open, etc.

One example of how we could use this would be to limit the grids to the active window client area by default (or provide a separate command for that, or make it configurable).

**Comment by synkarius** [comment]
All of the window-pinging stuff has been moved to the AutoSwitcher class in control.py now, FYI.

I agree though, that access to that other info from Windows would be very useful. How difficult would it be to ensure that this is Vista-compatible until MS no longer supports Vista? (If it's not the sort of nightmare that supporting IE7 was, it'd be nice to support whatever MS supports.)

**Comment by chilimangoes** [comment]
These are core APIs that have changed very little since Windows 2000 (95 in some cases). I'm actually more uncertain about supporting Windows 8, with it's funky start menu. I have no idea how that thing works or if it uses a mechanism completely different from the standard windowing APIs. But that's what VMs are for. I'll test it thoroughly on Vista through 10. Which reminds me, I should do the same with the current grid stuff in working on.

**Comment by LexiconCode** [comment]
I believe [this script](https://github.com/Danesprite/windows-fun/blob/master/window%20change%20listener.py) contains most of what we need to implement window change listener.

**Comment by LexiconCode** [comment]
Closing issue due to age if interest picks up again feel free to reopen.
