### ISSUE TITLE
Additional Line Ops

### ISSUE THREAD

**Issue by synkarius** [dictation-toolbox/Caster#133]
- move the "jump" commands into IDE command sets for more power
- "shackle" multiple lines (IDE command sets)
- IDE "configure" command
- the "periodic" command (CAUTION, do not "periodic" more than one command at a time, results become unpredictable)
- expand "find" to: word, characters, limited regex support, and letter(s 1-3)

**Comment by kendonB** [comment]
Closing old issue. If someone reads this and thinks the above features would be useful please open a new issue.
