### ISSUE TITLE
MouseGrids doesn't always seem to focus

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#171]
However, I'm unable to replicate this. The behavior is that sometimes the grid  program is focused on top, and works as expected, but sometimes it is not focused on top (but is still visible) and I have to use "switch window" to get it to work. If I can get this to happen consistently I will let you know.

**Comment by chilimangoes** [comment]
I've noticed the same thing occasionally, but it never happens consistently. I'll try to remember to take a look later and see if there's an easy way to force the grid window to have focus.

**Comment by seekM** [comment]
I noticed the same for Rainbow. I jused "kick" as a workaround.

**Comment by kendonB** [comment]
I am unable to use "kick" when using Legion. It will simply click on the app in focus. The only workaround I have is to use switch window.

**Comment by guidugli** [comment]
I am a new caster user and spent quite some time testing the rainbow grid. Just after trying several times I noticed that it is often not in focus. When I click with the mouse then it works.

**Comment by LazoCoder** [comment]
See #194 

> I've resolved the foreground issue by going into regedit, navigating to Computer\HKEY_CURRENT_USER\Control Panel\Desktop and changing the value of ForegroundLockTimeout to 0. Now the grid systems always load in the foreground.

**Comment by LexiconCode** [comment]
#194 workaround no longer works with Windows.

**Comment by kendonB** [comment]
`StartApp` now has a `focus_after_start` argument which hopefully will fix this
