### ISSUE TITLE
Feature suggestion: allow for different phrasing of numbers

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#174]
For example, I am unable to say "numb one thirty five", and have to say "numb one hundred and thirty five". For six digit numbers, it is much simpler to dictate the individual digits.

**Comment by synkarius** [comment]
This request should be made at the [Dragonfly repo](https://github.com/t4ngo/dragonfly). Caster uses Dragonfly's number pronunciation code.

**Comment by chilimangoes** [comment]
I commented on the dragonfly issue you opened, but I'm pasting the same comment here for reference, since I think this might be addressed at least partially in Caster. I already have a partially working example of my suggested fix below, but it needs a little work still.

> If there is a trivial way to write a grammar for this, I haven't been able to find it. I think a big part of the problem is the ambiguity in how (at least for English speakers) we say long numbers.

> For example, say I have the number 304027. The "correct" way of saying this would be "three hundred and four thousand and twenty seven". It also seems to be the only way to say 304027 and have it be recognized as a single number in a dragonfly grammar. But, in English, we might say something like "three oh four oh two seven" or "thirty forty twenty seven". In dictation mode, Dragon NaturallySpeaking does its best to try to figure out what you meant, using some kind of heuristics. But those same heuristics don't seem to be applied to numbers used in dragonfly grammars.

> I spent a fair amount of time at one point last year trying to modify my copy of the `numbers.py` grammar in Caster to support this. I created a rule definition that was something like "numb <n1> [<n2>] [<n3>] [<n4>] [<n5>]" which worked most of the time but also produced the wrong results fairly often. A couple of the failure modes that I remember were, for example, if you said "thirty forty twenty seven", it might be interpreted as either "30 40 27" or "30 40 20 7" and if you said "two hundred fifteen", it might be interpreted as "215", "200 15", "2 115", or "2 100 15". I remember I tried a variety of things to get around these ambiguity issues, and I was able to resolve some of them, but in the end it was more trouble than it was worth.

> @kendonB I think what I might do is just create a rule that allows you to quickly string together a list of single digits 0-9, like the "three oh four oh two seven" example. It's not as flexible, and won't allow you to say things like "thirty forty twenty seven", but it should at least resolve the problem of ambiguity.

**Comment by LexiconCode** [comment]
Consider this closed as its not related to Castor but Dragonfly.

**Comment by LexiconCode** [comment]
@kendonB this is now implemented in dragonfly. https://github.com/dictation-toolbox/dragonfly/pull/71

**Comment by kendonB** [comment]
@lexiconcode thanks heaps - I will try this out in the coming days.

**Comment by kendonB** [comment]
This one is now possible for numbers up to 9999 using `ShortIntegerRef` from dragonfly. I'm yet to come across a situation where I really need to say a larger number. The only use case that really needs it is when using "go to line n" in a very large document. Otherwise, repeated invocations of "numb" are just fine.

However, we have `IntegerRefST` which has something extra which I'm hoping @LexiconCode can educate us on.

**Comment by LexiconCode** [comment]
> However, we have `IntegerRefST` which has something extra which I'm hoping @LexiconCode can educate us on.

I'm not 100% sure to be honest. https://github.com/dictation-toolbox/Caster/blob/c21a9f8034b432ad3247362d3c92c4dc0e7a21bd/castervoice/lib/dfplus/additions.py#L10 the class IntegerContentST(IntegerContentBase): Looks like it's utilized for Integer Remap feature.

If we can remove it altogether I would be okay with that. However I don't want there to be negative impact on utilizing filter rules.

We should open this discussion in a new topic as it's implemented in dragonfly.
