### ISSUE TITLE
Formatted dictated text within larger output text

### ISSUE THREAD

**Issue by codingApprentice** [dictation-toolbox/Caster#183]
I have only recently started to use Caster, and I'm fairly new to Python programming, so this may be a very simple issue that I'm having.

I've been trying to add an encapsulate command within the Java ccr file as follows (I'm only including lines that I have changed):

`from dragonfly import Key, Text, Paste, MappingRule, Dictation, Function
#more imports

from caster.lib import textformat

#nonJava class
class Java(MergeRule):
    auto = [".java"]
    non = JavaNon
        
    mapping = {
              #some mappings 
            #my rule for encapsulation 
           "(encapsulated | encapsulate) word [<text>]": R(Text("public String get" + str(textformat.prior_text_format("%(text)s")) + "(){}") +\
			                                        Key("left") + Key("enter") + Key("tab") + \
								Text("return" + str(textformat.prior_text_format("%(text)s")) + ";") + \
								Key("enter") + Key("right") + Key("enter:2") + \
								Text("public String set" + str(textformat.prior_text_format("%(text)s"))) + \
								Text("(String " + str(textformat.prior_text_format("%(text)s")) + "){}") + \
								Key("left") + Key("enter") + Key("tab") + \
								Text("this." + str(textformat.prior_text_format("%(text)s")) + " = " + str(textformat.prior_text_format("%(text)s")) + ";") + \
								Key("enter") + Key("right") + Key("enter:2"), 
								rdescript="Java: encapsulate string variable")
}
extras   = [
		Dictation("text"),
		]
    defaults = {
		"text": ""
		}

#some code`
___________
I had intended to first say the caster command "set format <capitalisation> <spacing> bow" followed by my encapsulate command e.g. "encapsulate word hello world",but what I get back,is the following:

`public String getNone(){
	returnNone;
}

public String setNone(String None){
	this.None = None;
}`

So str(textformat.prior_text_format("%(text)s")) is returning none.
Digging through the textformat.py file, I tried this function instead as it looked like it would return a text or string instead of none:
`str(textformat.get_formatted_text(2,1,"%(text)s"))`
but then I get a whole bunch of errors from natlink when I try to speak the command (see bottom of page).

Is what I'm trying to do even possible? or is there something that I'm not understanding?
Note: I tried replacing text with textnv, as that seems to be something that was mentioned in the error,but to no avail.
Many thanks in advance.

_____________
ERROR:action.exec:Text('public String get%(Text)S(){}', dynamic): Spec 'public String get%(Text)S(){}' doesn't match data {'nnavi500': 1, 'nnavi50': 1, 'capitalization': 0, 'text': NatlinkDictationContainer(hello, world), '_grammar': <dragonfly.grammar.grammar_base.Grammar object at 0x10CE8850>, 'textnv': '', '_rule': <caster.lib.dfplus.merge.mergerule.MergeRule object at 0x10F5AD50>, 'mtn_mode': None, 'mtn_dir': 'right', '_node': <dragonfly.grammar.state.Node object at 0x10D06998>, 'n': 1, 'spacing': 0, 'big': '', 'npunc': 1, 'extreme': None}.
ERROR:action.exec:Execution failed: Text('public String get%(Text)S(){}', dynamic)
ERROR:action.exec:Text('return%(Text)S;', dynamic): Spec 'return%(Text)S;' doesn't match data {'nnavi500': 1, 'nnavi50': 1, 'capitalization': 0, 'text': NatlinkDictationContainer(hello, world), '_grammar': <dragonfly.grammar.grammar_base.Grammar object at 0x10CE8850>, 'textnv': '', '_rule': <caster.lib.dfplus.merge.mergerule.MergeRule object at 0x10F5AD50>, 'mtn_mode': None, 'mtn_dir': 'right', '_node': <dragonfly.grammar.state.Node object at 0x10D06998>, 'n': 1, 'spacing': 0, 'big': '', 'npunc': 1, 'extreme': None}.
ERROR:action.exec:Execution failed: Text('return%(Text)S;', dynamic)
ERROR:action.exec:Text('public String set%(Text)S', dynamic): Spec 'public String set%(Text)S' doesn't match data {'nnavi500': 1, 'nnavi50': 1, 'capitalization': 0, 'text': NatlinkDictationContainer(hello, world), '_grammar': <dragonfly.grammar.grammar_base.Grammar object at 0x10CE8850>, 'textnv': '', '_rule': <caster.lib.dfplus.merge.mergerule.MergeRule object at 0x10F5AD50>, 'mtn_mode': None, 'mtn_dir': 'right', '_node': <dragonfly.grammar.state.Node object at 0x10D06998>, 'n': 1, 'spacing': 0, 'big': '', 'npunc': 1, 'extreme': None}.
ERROR:action.exec:Execution failed: Text('public String set%(Text)S', dynamic)
ERROR:action.exec:Text('(String %(Text)S){}', dynamic): Spec '(String %(Text)S){}' doesn't match data {'nnavi500': 1, 'nnavi50': 1, 'capitalization': 0, 'text': NatlinkDictationContainer(hello, world), '_grammar': <dragonfly.grammar.grammar_base.Grammar object at 0x10CE8850>, 'textnv': '', '_rule': <caster.lib.dfplus.merge.mergerule.MergeRule object at 0x10F5AD50>, 'mtn_mode': None, 'mtn_dir': 'right', '_node': <dragonfly.grammar.state.Node object at 0x10D06998>, 'n': 1, 'spacing': 0, 'big': '', 'npunc': 1, 'extreme': None}.
ERROR:action.exec:Execution failed: Text('(String %(Text)S){}', dynamic)
ERROR:action.exec:Text('this.%(Text)S = %(Text)S;', dynamic): Spec 'this.%(Text)S = %(Text)S;' doesn't match data {'nnavi500': 1, 'nnavi50': 1, 'capitalization': 0, 'text': NatlinkDictationContainer(hello, world), '_grammar': <dragonfly.grammar.grammar_base.Grammar object at 0x10CE8850>, 'textnv': '', '_rule': <caster.lib.dfplus.merge.mergerule.MergeRule object at 0x10F5AD50>, 'mtn_mode': None, 'mtn_dir': 'right', '_node': <dragonfly.grammar.state.Node object at 0x10D06998>, 'n': 1, 'spacing': 0, 'big': '', 'npunc': 1, 'extreme': None}.
ERROR:action.exec:Execution failed: Text('this.%(Text)S = %(Text)S;', dynamic)

**Comment by LexiconCode** [comment]
Upload the file in its complete form and I'll take a look.

**Comment by codingApprentice** [comment]
I've included my Java ccr file now in my own fork, if that helps people to diagnose what's going wrong.
[Caster - my fork - Java ccr](https://github.com/codingApprentice/caster/tree/master/caster/lib/ccr/java)

thanks.

**Comment by LexiconCode** [comment]
I’m new to programming as well but I’ll take a look aay after tomorrow.

**Comment by LexiconCode** [comment]
I'm closing this because it's old and can be reopened if there's interest.
