### ISSUE TITLE
Documentation for Yapf support by editor.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#209]
I've done some research regarding Yapf support by editor. The goal is to provide Caster contributors the documentation to utilize [Yapf](https://github.com/google/yapf) formatting for their favorite editor/IDE. Then I will go through and implement shortcuts to use the plugins. I've looked for look for native support editors for yapf then fall back to plug-ins in its absence.

**[Yapf](https://github.com/google/yapf)** 
[VSCode](https://donjayamanne.github.io/pythonVSCodeDocs/docs/formatting/)
[Visual Studio IDE*](https://docs.microsoft.com/en-us/visualstudio/python/formatting-python-code)
[Sublime](https://github.com/jason-kane/PyYapf)
Notepad*++
[Jetbrains](https://github.com/binh-vu/yapf-pycharm) *
[Atom](https://atom.io/packages/atom-beautify), [1](https://atom.io/packages/ide-python)
[Eclipse](https://marketplace.eclipse.org/content/pydev-python-ide-eclipse)
[Emacs](https://github.com/JorisE/yapfify)

* Jetbrains plug-in is nonfunctional and an alternative is needed.
* Notepad++ - A clean solution is needed for formatting Python with yapf. Suggestions are welcome!
* Visual Studio IDE - Links to the official documentation regarding format style but no plugging available for yapf. ATM

I've not tested to each of these plug-ins or configurations and will need help from the community to verify viability. When feedback is provided and each editor is tested it will we will discuss including it in the Castor documentation. Note certain editors or plug-ins may have specific instructions to utilize Yapf. Please defer to their documentation.

_The formatting guidelines have not been finalize._
 Consider the following configuration provided as draft. Yapf style format [style.yapf](https://github.com/synkarius/caster/blob/master/.style.yapf)

**Setup Yapf Style by project configuration.** 
Cloning or downloading the caster project the [.style.yapf](https://github.com/synkarius/caster/blob/master/.style.yapf) already included in the root directory.

**Setup Instructions for Yapf Style global configuration.** 
This allows global style for all Python projects. If a project has `.style.yapf` it will take precedence over global configuration.

Windows*
[style.yapf](https://github.com/synkarius/caster/blob/master/.style.yapf) and put a copy of it in `%USERPROFILE%\.config\yapf`

Windows Subsystem for Linux user `root` `%USERPROFILE%\AppData\Local\Lxss\rootfs\.config\yapf`

UNIX
[style.yapf](https://github.com/synkarius/caster/blob/master/.style.yapf) and put a copy of it in  `~/.config/yapf/style` file in your home directory.

You may have to create folders for the directory path if they do not exist.
* [How](https://gist.github.com/ozh/4131243) to create a folder preceded by dot e.g `.config` in Windows.

[Yapf](https://github.com/google/yapf) as further instructions for command line and directory specific Styling.
@Versatilus has credit for install instructions

**Comment by LexiconCode** [comment]
@Versatilus let me know what you think.

**Comment by Versatilus** [comment]
This looks good. As soon as we finalize a style, we should link to it here.

**Comment by Versatilus** [comment]
I recently realized the last line of that configuration file is wrong. It should be:
```
no_spaces_around_selected_binary_operators=*,/
```

**Comment by LexiconCode** [comment]
Fortunately it's correct in the master repository. 
https://github.com/synkarius/caster/blob/master/.style.yapf

I'll edit the post since the correct version already integrated into master branch.

**Comment by Versatilus** [comment]
By the way, `atom-beautify` seems to ignore the local configuration file, so it might be a good idea for some people to run it from the command line.
