### ISSUE TITLE
Consolidating command phrases from applications into core CCR and Application Core

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#211]
I have been working on the API and reviewing many of the commands across different editors. There are identical commands across editers with varying degrees of implementation that are app specific. These are seen both at the castor core and supported applications. 

The idea is to have one command phrase per command set. Yet still preserve AppContext per application for each implementation not creating a global grammar.

This approach has some advantages.
- Enforces standard command phrases across all applications.
- Provides easy customization by end-user one command phrase per command set utilizing filter rules.
- Command phrases that are in for example `atom.py` are unique to that application.
- Eliminates duplicate command phrases conflicts.
- Simplifies documentation 

An example of duplicate commands that have the same functionality across different applications.
```
"next tab [<n>]":     R(Key("c-f6"), rdescript="Eclipse: Next Tab") * Repeat(extra="n"),
"next pane":          R(Key("cs-p") + Text("Window: Focus Next Pane") + Pause(atom_palette_wait) + Key("enter"), rdescript="Atom: Next Pane"),
"nexta [<n>]":        R(Key("c-pgdown"), rdescript="Visual Studio Code: Next Tab") * Repeat(extra="n"), 
"next tab [<n>]":     R(Key("c-tab"), rdescript="Foxit Reader: Next Tab") * Repeat(extra="n"),
"next tab [<n>]":     R(Key("c-tab"), rdescript="SSMS: Next Tab") * Repeat(extra="n"),
"next tab [<n>]":     R(Key("ca-pgdown"), rdescript="Visual Studio: Next Tab") * Repeat(extra="n"),
```

Let's move these out of their individual applications into ApplicationCore.py or CCR core. Application Core `.\caster\apps\ApplicationCore.py` could be a file created containing the commands that don't fit within CCR core. Commands that don't have duplicate functionality or that are unique a application still reside within their <ApplicationName>.py

Very pseudo-representation of  a `command set` in `ApplicationCore.py` 
```
"next tab [<n>]":  {
          R(Key("c-f6"), rdescript="Eclipse: Next Tab") * Repeat(extra="n"),
          R(Key("cs-p") + Text("Window: Focus Next Pane") + Pause(atom_palette_wait) + Key("enter"), rdescript="Atom: Next Pane"),
          R(Key("c-pgdown"), rdescript="Visual Studio Code: Next Tab") * Repeat(extra="n"), 
          R(Key("c-tab"), rdescript="Foxit Reader: Next Tab") * Repeat(extra="n"),
          R(Key("c-tab"), rdescript="SSMS: Next Tab") * Repeat(extra="n"),
          R(Key("ca-pgdown"), rdescript="Visual Studio: Next Tab") * Repeat(extra="n"),
}
```

The example above doesn't show how to implement preserving AppContext per individual implementation.
This is a significant change within Castor. I would appreciate feedback from everybody even if they're not actively involved in developing Caster at this moment in time. 

In theory this could be done for CCR Programming languages as well. Of course that's a separate ticket but the framework in mind here could support both.

**Comment by LexiconCode** [comment]
Every application could be represented in command sets supported or not implemented in `ApplicationCore.py` or CCR.

 A placeholder could be implemented when a command is spoken that is not supported or implemented notifying the user.  That way the user is not the reason why a command not work and X application. Notifications could have 2 states.  Not supported means that the functionality does not exist in the application. Not implemented means functionality exists but is not yet implemented.

**Comment by Versatilus** [comment]
I agree with this in principle. We need to be careful with tab navigation because there are often different types of tabs in the same application, especially for development environments.

An idea related to this that I've been tossing around in my head is more dynamic configuration through JSON files. Before I waste time on that I need to do a refresher on user-defined filters.

**Comment by LexiconCode** [comment]
That's the point that allows the user to customize their approach across all supported programs. If a particular program deviates too much a separate command phrase can be created. That would be moved into 

> Command phrases that are in for example atom.py are unique to that application.

I think the ideas twofold unifying command sets that are common for most dev environments to one file and easing user configuration one command phrase to a command to set. I'd have to look up user-defined filters myself as well.

**Comment by LexiconCode** [comment]
This would be a separate issue but it is related in how we view commands and their context.

If command `A` is spoken only command` B, C and D` are available commands for recognition. 
this allows us to get very specific per application about the context of how things are used. More importantly it allows us to use duplicate command phrases that have different meanings per environment.

**Comment by Danesprite** [comment]
This is a pretty interesting idea! As you say, it's a good way to eliminate command duplication across grammars, amongst other things. One way to implement this would be to query `ApplicationCore` for any mappings to add to `MergeRule.mapping` before merging:
``` Python
command_set = {}  # as in the above pseudo-representation

def query_command_phrases(rule):
    result = {}

    def matching_action(action):
        # E.g. "Eclipse: Next Tab" starts with "Eclipse"
        return action.rdescript.lower().startswith(rule.get_pronunciation().lower())

    for spec, actions in command_set.items():
        matches = list(filter(matching_action, actions))
        if matches:
            result[spec] = matches[0]
    return result
```
You might use it in `MergeRule.__init__`: `mapping.update(query_command_phrases(self))` or somewhere in `ccrmerger.py`. Some validation of the `rdescript` value might be a good idea, perhaps with a subclass of `RegisteredAction`.

As for cases where functionality is not implemented for an application, `query_command_phrases` could be modified to return a dictionary with the spec and a default not implemented / not supported action. The default actions could notify the user somehow that the command isn't valid for the current application. Before updating `MergeRule.mapping` with a default value, it should be checked that a proper spec -> action mapping isn't about to be replaced.

**Comment by LexiconCode** [comment]
A refresher on how [Rule Filters Work](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/examples/rules/Caster%20Rules/). That being said the proposed change would simplify Rule filters for the end-user as well.

**Comment by LexiconCode** [comment]
Another approach might be easier.  We could directly implement the standard for spec as implemented for CCR. This does away with the idea of command sets as stated in the opening post. Yet this approach does achieve many of the goals outlined in the op.

appcore.py in Apps folder

```python
class ApplicationCore(object):

    CLOSE_TAB = "close pane"

# not part of the ApplicationCore standard:
CANCEL = "(terminate | escape)"

@staticmethod
def set_cancel_word(spec):
    ApplicationCore.CANCEL = spec
```

For instance atom.py

```python
        from caster.apps.appcore import EditorSpecs
        
        EditorSpecs.CLOSE_TAB:
            R(palettized("Pane Close"), rdescript="Atom: Close Pane"),
```

The only real downside is it moves away from what people are use to seeing in a traditional dragonfly grammar. That in itself creates barriers for adoption.

Implementing this idea would involve us going through the supported applications and agreeing upon standard spec(command name) for all editor/IDE functions that are commonplace. Keep in mind we should use filter rules if we want to rename specs due to personal preference. 

Once that's done we can create a template for people to add IDE's or other classes of programs such as browsers.

**Comment by mrob95** [comment]
Would this approach have any advantages over simply reorganising the IDE command sets so that commands which are common across IDEs have the same trigger phrase and are grouped together at the top of the file?

If there are commands which appear in multiple IDEs with the same execution keypress then I could see a case for making a separate command which would return a dictionary of specified standard commands, to cut down on repetition. Otherwise I'm not sure it would be worth it – you'd just be specifying the same commands in a different file, making the whole thing more complicated and less easy to assess at a glance.

**Comment by LexiconCode** [comment]
@mrob95 
By design the CCR for language syntax has been standardized. This makes it helpful when going across different languages in the same could be said for Programs. So for all CCR files that have been added utilize `standard.py` Simply reorganizing standard doesn't enforce standard naming schemes for specs by design. When a user adds a new program language CCR they are forced to think what is standard across all languages and what is language specific. 

I think including example template for programs with well documented comments would help people bridge the differences between Caster and dragonfly.
