### ISSUE TITLE
Redesign of Registered Actions with additional properties

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#235]
These are some thoughts I've had on adding more metadata to [Registered Actions](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/examples/rules/Caster%20Rules/#the-context-stack). [Current Code implementation](https://github.com/synkarius/caster/blob/42a7c9cc64201ea71fc1a66d3e29790106e76701/caster/lib/dfplus/state/actions.py)

Currently Registered Actions provide the following but further detail in docs. 

- Registration with various printing services (such as the Python console, the status window, or loggers) allowing to see which actions executed, or that they have executed.
- Registration can be used mark a command as a part of another command. This is one significant difference between Caster and Dragonfly. Dragonfly commands are once-and-done. Caster commands can interact with other commands which have been spoken in the past or will be spoken in the future. In order to use this functionality, we set the rspec property of the R action.

The design should include [automatic document generation](https://github.com/synkarius/caster/issues/234), API, GUI interface, and [Consolidating command phrases](https://github.com/synkarius/caster/issues/211). In addition this should also simplify writing caster rules.

Overarching design thoughts for additional properties

- Properties may be toggled to not show up within logging/natlink window
- Properties may be optional but have default values and formatting.

Truncated code from Atom.py formatted for clarity

```python
# Utilizes the Palette UI to leverage commands.
def palettized(function_text):
    return Key("cs-p") + Text(function_text) + Pause(atom_palette_wait) + Key("enter")

class AtomRule(MergeRule):
    pronunciation = "atom"
```

```python
    # ----------Spoken Command/Action-----------------> Shortcut keys----------> #Displayed Text
#Basic Cursor Navigation
    "up [<n>]":
        R(Key("up"), rdescript="Atom: Move Cursor Up #")*Repeat(extra="n"),
#Basic White Text Manipulation
    "tab|indent [<n>]":
        R(Key("tab"), rdescript="Atom: Press Tab Key #")*Repeat(extra="n"),
    "space [<n>]":
        R(Key("space"), rdescript="Atom: Press Tab Key #")*Repeat(extra="n"),
# Menu UI-----------------------------------------------------------------------------------
    #File Menu
    "[open] new window":
        R(Key("cs-n"), rdescript="Atom: New Window"),
#Script
    "script run":
        R(palettized("Script: Run"), rdescript="Atom: Script: run"),
#Git Plus
    "git checkout [branch|tag]":
        R(palettized("Git Plus: Checkout"),
          rdescript="Atom: Git Checkout Branch|Tag"),
```

1. A paper cut issue Command phrases and writing rdescript 

```python
"[open] new window":
    R(Key("cs-n"), rdescript="Atom: New Window"),
```

Notice that `rdescript "New Window"` almost matches the command phrase `[open] new window'. So let's simplify. Why define rdescript unless you have to? The proposed change if rdescript Is not defined by default It uses the command phrase with each word Uppercased.

2. Notice rdescript also contains useful information such as the application name `Atom:`. Let's move that into a new property. So it doesn't have to be defined for every command less specified such as global or and others string. The default would be ApplicationRule Name `AtomRule(name="atom")` or app context executable `context = AppContext(executable="atom", title="Atom")`.
3. Add the Optional property that is true or false denoting at the command is available in an API. `API=False` Defaults to false when undefined or absent. Useful for when documentation is generated to denote that an API is available for the command. Could be utilized for other purposes.
4. Add a property or to that signifies command classification `White Text Manipulation` either for a command or an app extension `Script:`  Could be used for automatic documentation.

```python
"script run":
    R(palettized("Script: Run"), rdescript="Atom: Script: run"),
#Basic White Text Manipulation
    "tab|indent [<n>]":
        R(Key("tab"), rdescript="Atom: Press Tab Key #")*Repeat(extra="n"),
    "space [<n>]":
        R(Key("space"), rdescript="Atom: Press Tab Key #")*Repeat(extra="n"),
```

These thoughts need to be taken account with the concept of consolidating command phrases and the traditional application grammars. Anyway I thought you guys might bring some feedback.

**Comment by gerrish** [comment]
I'd like all of them. They would make writing a new Grammar much less annoying. Another Idea which would be useful would be to create idefault nterfaces(mapping) which the user will be able to override. For example,a default programming interface would include all the keywords in standard.py mapped to explanatory text. `shells: else` 
This would be a great starting point for creating new grammars and will encourage the use of common command phrSes.
