### ISSUE TITLE
Community Resources

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#237]
This is a place to post things that you find useful with the intent of adding them into a section of documentation of Caster for resources. I'm not talking about supported applications in Caster although if you have add-ons do mention them. Everything from guides, websites, repositories, software, hardware, and workflows that enhance your productivity or knowledge of programming. 

When posting a resource include:

- A link to the resource.
- Whether it's open source, commercial, personal use if applicable.
- Cost of ownership cost if applicable.
- How long have you been using the use resource and frequency that you use it.
- Optionally are you currently seeking for alternatives the posted resource? Have you used any other alternatives before finding the resource?
- Most importantly your experience with or what you get out of the resource personally? Try not the state a feature list but the features you find useful and expound on that. Any pros and cons?
- Try to maintain similar formatting as in the examples below.
  If you update your resource please mention `LexiconCode`. The state the date and content that you edited. 

**Community Resources**

**Apps**

By [@LexiconCode](https://github.com/LexiconCode) 

- [Fast Keys](https://www.fastkeysautomation.com/) Commercial, 19$ for 3 computers lifetime license. 
  I've used Fast Keys as a text expander for 4 years daily. I bought it for $10. Most of my dictation is done by voice but for the bit that I do interact with the computer is augmented by Fast Keys. I have created a shorthand for filling in emails and forms. Other aspects I appreciate is the simple interface, light on resources (RAM 2 MB), extensibility, not being integrated into the cloud. I've before purchasing Fast Keys I looked into/experimented with Text Expander, Phrase Expander, Breevy. I didn't know about at the time of purchase of Fast Keys Autohotkey as a open source alternative. 

- [GitExtensions ](https://gitextensions.github.io/) Open Source Free
  Almost daily for about a year and it has boosted my productivity. Unofficially Supported with DNS Select-and-Say for enhanced navigation menus and text. GitExtensions a GUI interface as a replacement for commandline for Git. While many IDE's/editors now integrate Git commands I still find myself coming back to GitExtensions. The program is well laid out and intuitive. I spend less time thinking about the commands of git and more about the functionality that I need. I wish it had more default keyboard commands. What I most appreciate most actions can be easily reverted. I'm overall inexperienced with Git and often become frustrated. This is a salve for weary bones.

- [Window Focus Logger](http://www.adminscope.com/downloads/window-focus-logger/) - Close Source - Free for personal and commercial use
	I use this to help debug application stealing focus unexpectedly. It can run in the background logging windows including window titles and process's location. Perhaps the most useful feature is it that only tells you in a interface is in focus but if it's keyboard focused as well.

By @LazoCoder 

- [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en)(Plug-in for Google Chrome) Open Source Free

  This is a plug-in for Google Chrome that I use everyday. It finds all the links on a webpage and highlights them so that you can select them with letters on the keyboard (or voice) instead of clicking them with a mouse. It makes browsing the web by voice quick and seamless. I use it when I'm making Google searches, browsing Reddit, email, and pretty much everything else on the internet. Prior to discovering this plug-in, I used to use the "douglas" and "legion" grid systems to click things in the browser, but this is incredibly slow in comparison to Vimium.

The setup that I personally use is as follows. Go into Vimium's settings and copy and paste the following into "Custom key mappings":

```
unmapAll
map \ LinkHints.activateModeToOpenInNewTab
map / LinkHints.activateMode
map s scrollPageUp
map d scrollPageDown
map ? showHelp
```

  Now you can say "slash" to open a link or "backslash" to open it in a new tab. Furthermore, uttering the words "sierra" and "delta" move the page up and down respectively. These four commands are the only ones that I use, and they make a world of difference for me.

- Surfingkeys a Plug-in for [FireFox](https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/ )/[Google Chrome](https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc?hl=en-US) - Open Source Free

  People may already be aware of it, but I've got a fair bit of use out of an extension called SurfingKeys, which provides vim-like shortcuts for a lot of browser functionality, including hints for links and input fields, searching through bookmarks, moving the current tab to a new window, and a load of other stuff.

By @TTeig 

+ [+7 Taskbar Number](https://rammichael.com/7-taskbar-numberer) - Close source - Free

![](https://rammichael.com/wp-content/uploads/2012/07/7-Taskbar-Numberer.png)

  I have used it every day for about a month. It numbers your windows and tray icons and makes it so much easier to navigate between them. I was hesitant because there was no source code or license, but it was just too useful. I would like something more customizable and open source, but it does the job and I haven't seen any alternatives. (There are also other little useful tools from the creator that I haven't tried)

 **Workflow**

By @LexiconCode 

- To rebase **all** local branches on upstream/master in git bash: - [Source](https://wtanaka.com/node/8244)

```
BASEBRANCH=upstream/master
git for-each-ref --shell --format="git rebase $BASEBRANCH %(refname:short)" refs/heads/ | sh -x
```

Often I have a lot of working branches the need to be up-to-date with the development branch of Caster. This cuts out some of the time of rebasing but currently does not push to the origin branches. So enhancements could be made. When experimenting **backup your local repository**. This may not work as intended if you have a local branch like `gh-pages` with `C:\NatLink\NatLink\MacroSystem` your working directory git.

By @Versatilus 

- Procedures for maintaining Dragon NaturallySpeaking Accuracy

  One thing I do to help with accuracy whenever I make a new profile is that I dictate specific documents back into a text editor, correcting mistakes as I go. The [documents](https://www.google.com/search?q=speech+therapy+reading+passages+for+adults) are several short passages created by speech therapists specifically to help people with pronunciation. I'll look in a little while for links to a few of them.

  Additionally, I make a list of words that I consistently have issues with as I go and explicitly add them to the vocabulary (by saying "edit vocabulary"). I also make up random sentences containing the conflicting words and dictate those into a text editor. If I'm feeling proactive, I do this with other commands, even if I'm not specifically having problems with them.

  During this time I also spent extra time dictating things like documentation and detailed forum posts. I do most of my dictation in a text editor and make sure to save the files so that Dragon can use them to adapt to my speech patterns.

  It's important to frequently run Dragon's accuracy tuner during this process, then occasionally after that as well.

------

How to get help outside of an github issue.

- For those that prefer text-only utilize for general questions and to share your experience go to the [Caster Gitter Chat Channel](https://github.com/dictation-toolbox/Caster).

**Comment by LazoCoder** [comment]
[Vimium](https://vimium.github.io/) Open Source Free

This is a plug-in for Google Chrome that I use everyday. It finds all the links on a webpage and highlights them so that you can select them with letters on the keyboard (or voice) instead of clicking them with a mouse. It makes browsing the web by voice quick and seamless. I use it when I'm making Google searches, browsing Reddit, email, and pretty much everything else on the internet. Prior to discovering this plug-in, I used to use the "douglas" and "legion" grid systems to click things in the browser, but this is incredibly slow in comparison to Vimium.

The setup that I personally use is as follows. Go into Vimium's settings and copy and paste the following into "Custom key mappings":
```
unmapAll
map \ LinkHints.activateModeToOpenInNewTab
map / LinkHints.activateMode
map s scrollPageUp
map d scrollPageDown
map ? showHelp
```
Now you can say "slash" to open a link or "backslash" to open it in a new tab. Furthermore, uttering the words "sierra" and "delta" move the page up and down respectively. These four commands are the only ones that I use, and they make a world of difference for me.

**Comment by LexiconCode** [comment]
**Change Log**
6-21- 018
_Added_ Vimium Open Source Free by @LazoCoder

**Comment by TTeig** [comment]
[7+ Taskbar Numberer](https://rammichael.com/7-taskbar-numberer)
Close source, free, no license.
I have used it every day for about a month. It numbers your windows and tray icons and makes it so much easier to navigate between them. I was hesitant because there was no source code or license, but it was just too useful. I would like something more customisable and open source, but it does the job and I haven't seen any alternatives. (There are also other little useful tools from the creator that I haven't tried)
