### ISSUE TITLE
Update Caster's Github Pages

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#294]
[Github Pages](https://pages.github.com/) allows us to host for free a website through Github to display projects.

[Caster Github Page](http://synkarius.github.io/caster/) 
We need to update the format. 
- Focusing on displaying Castor's features and capabilities. 
- Highlighting supported programs and languages
- Links for install
- Getting started...(navigating the Caster project)(Examples of coding by voice)
- Guide for customizing - filter rules
- Contributing guidelines

Some of these resources need to be created. They need to be simple and clean. Some can be done through video format or Text. Bottom line we need the presentation to be professional and elegant. The documentation to be straightforward yet simple. Which will guide the user into the read the docs for more in depth documentation.

There are 3 types of groups of people that come to this Caster. The professional programmer, the programming student, and the nonprogrammer usually with a acute or chronic disability. That being said programming resources should also be included within the documentation.

One key aspect is I want people without a disability to think to utilize their voice to augment their development environment. I strongly believe that people would find Caster beneficial and will draw people with experience to the project. This should not come at an expense of the 3 groups named above.

**Comment by mrob95** [comment]
First step might be to expand the readme to include a summary of the features which Caster offers and example commands. From the home page at the moment it isn't immediately obvious what it is for or what it can do. I'll give it some thought.

**Comment by esc123** [comment]
Definitely agree that Casters readme needs an update. And as I don't code much this is at least something I could contribute to. @LexiconCode you are spot on about the different groups of people who get interested in caster and I would be interested in getting the documentation to reflect that by accommodating coders and non-coders alike. If any input or help is required please let me know!

**Comment by LexiconCode** [comment]
I think the readme is reasonable place to start. I'm working on fixing markdown formatting the rest the documentation first. Once that's done will start on the readme.

**Comment by kendonB** [comment]
Docs are here https://caster.readthedocs.io/. Closing old issue.
