### ISSUE TITLE
Mirror Casters github repository for redundancy

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#300]
The ideas to mirror casters repository on another git repo service. Granted it is unlikely that github will sustain data loss or github would disappear overnight. Once redundancy is set up it should be relatively maintenance free.

So alternative services could be suggested.
@codingApprentice mentioned [Bitbucket](https://bitbucket.org/).
[Keep in sync your Git repos on GitHub, GitLab & Bitbucket](https://moox.io/blog/keep-in-sync-git-repos-on-github-gitlab-bitbucket/)
[Backup-on-the-go](https://github.com/xuhdev/backup-on-the-go#readme)
[How to keep two Git repositories in sync](https://www.opentechguides.com/how-to/article/git/177/git-sync-repos.html)

**Comment by kendonB** [comment]
I have made https://gitlab.com/kendonb/caster and am updating using the suggestion from @codingApprentice. It was quite easy. Of course, any updates that occur from my last push won't be synced. I'm also not terribly concerned as people obviously keep copies on their home computers as well.

@LexiconCode feel free to reopen if you want to make your own backup.

**Comment by LexiconCode** [comment]
Perfect. You might want to [synchronize the issues](https://unito.io/blog/how-to-export-github-issues-to-gitlab-and-bitbucket/) as well is that something that we can't easily backup to our local repositories.

**Comment by kendonB** [comment]
That service isn't free - I haven't been able to find a good free method yet.

**Comment by LexiconCode** [comment]
Sorry I meant to link to stackchange.
