### ISSUE TITLE
Pylint and YAPF configuration

### ISSUE THREAD

**Issue by Versatilus** [dictation-toolbox/Caster#337]
@comodoro @LexiconCode
I'd be interested in finding out the rationale for the way the Pylint file is written. It doesn't look to be doing much in its current state.
Personally, I would set it up to flag areas that will cause problems with Python 3. With official support for Python 2 going away in 2020, I would like to get the code base to a point where it can successfully run on both the 2.7 and 3.4 (or higher) releases.

I'd also like to revisit the YAPF configuration we settled on. I'm starting to think the default line length is adequate. Generally speaking, when I go over the default of 79 characters it means that I should be refactoring the code somewhere to make things simpler. It certainly makes it easier to have two files open side-by-side on my 1920 by 1080 screen.
I've also realized that operator grouping looks good with numbers but it's just kind of weird with variables, especially when the operators have been overloaded.
Otherwise, I still find the rest of the formatting useful and pleasant.

I would really like everyone's opinions on this.

**Comment by comodoro** [comment]
@Versatilus The rationale behind .pylintrc was to first disable all reports except errors and then gradually enable some while improving the code. However it does have flaws as such changes would be massive and as far as I remember there were problems with pylintrc for Python 2, so a change might be desirable.

I agree that 79 characters looks better than 90, and in Python it is very often possible to do it (split lines) with parentheses. I read that sometimes they put parentheses just for this purpose.

I'm afraid I do not know what operator grouping is.

**Comment by LexiconCode** [comment]
Close due to inactivity, can be reopened.
