### ISSUE TITLE
Change imports to support Aenea

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/caster#345]
@Versatilus says: AppContext, Key, and Text should now be imported from caster.lib.context and caster.lib.actions to support optional use with Aenea.

@Versatilus which should be imported from which? And are there other functions that should also be switched?

**Comment by mrob95** [comment]
This may not be strictly necessary for Windows-only apps like gitbash. I'm not sure if anyone using Aenea would want to execute git commands on the virtual machine, but if they did then it would be better to leave it importing from dragonfly. Probably doesn't make much difference either way.

**Comment by kendonB** [comment]
If it still works either way then it's probably better to switch everything over to `caster.lib` - future coders copying code for new apps that they want to use with Aenea then have the right examples everywhere.
