### ISSUE TITLE
Compound spec option in words.txt?

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#347]
Ref: #341 

It would be great to be able to include multi-word commands in words.txt. The interface would be something like:
```
<<<COMPOUND_SPEC>>>
spec1,spec2 -> compound
```
very similar to the record from history command.

**Comment by LexiconCode** [comment]
I've discovered that you can actually replace entire specs using `words.txt`.

- if there's any extras in the spec those definitions need to be the same to match the original spec.
```
<<<ANY>>>
(lock Dragon | deactivate)  -> (sleep dragon | turn off) 
(lock Dragon | deactivate)  ->  turn off
lock Dragon  -> (sleep dragon | turn off)  
```
For some reason simplify transformers ignore specs with <text> may be a bug or by design more research is needed.
