### ISSUE TITLE
Weird bug when I try to replace "fly" 

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#354]
When trying to replace the word "fly" in `words.txt`, I get an odd error. My `words.txt`:

```
<<<NOT_SPECS>>>
fly -> new
```

```
UserDirectory: C:\Users\kendon\Documents\caster
UnimacroDirectory: C:\NatLink\Unimacro
start of natlinkstartup
Vocola not active
Global rule filter from file 'words.txt' activated ...
Error loading _caster from C:\Users\kendon\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 317, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\kendon\Documents\caster\_caster.py", line 152, in <module>
    gfilter.run_on(bring_rule)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\gfilter.py", line 231, in run_on
    spec_override_from_config(mp)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\gfilter.py", line 221, in spec_override_from_config
    rule._mcontext, rule._mwith)
TypeError: __init__() takes at most 7 arguments (11 given)
-- skip unchanged wrong grammar file: C:\Users\kendon\Documents\caster\_caster.py
-- skip unchanged wrong grammar file: C:\Users\kendon\Documents\caster\_caster.py
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1uniform
  DNS version: 15
  Python version: 27
  Windows Version: 7

User defined macro's (UserDirectory) enabled: C:\Users\kendon\Documents\caster
----------------------------------------

```

I do not get the same error when trying to replace `shin` or `queue`.

**Comment by comodoro** [comment]
I can reproduce. BringMeRule is SelfModifyingRule and has fewer constructor arguments; gfilter assumes MergeRule. Note that this is not specific to bring me. I can reproduce with "alias" added to word.txt <<<SPEC>>> for example.

Quick fix would probably be adding instance check to gfilter. I am not sure what to do with it long term as I mostly do not use filter rules.

**Comment by kendonB** [comment]
Both should be replacing words only IMO.

**Comment by synkarius** [comment]
@LexiconCode asked me to weigh in here. I think if you asked me what my original intent was, I would have said substrings. But I agree actually: replacing substrings is confusing and can lead to unpredictable behavior. It should be word replacement only.

**Comment by synkarius** [comment]
That said, you would of course also want the ability to replace whole phrases as well. Just not parts of words.

**Comment by LexiconCode** [comment]
@kendonB I can no longer replicate this error in the initial post with the rewrite 1.0.0

Let me know if it's fine for you and I'll close the issue.
