### ISSUE TITLE
Concise interface to modify "Choice" lists

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#355]
I'm trying to modify the list of functions in `r.py`. 

Would it make sense to have a subfolder of `/user` that contains all of these lists? Then the user can modify them there, rather than in the `r.py` source file.

**Comment by mrob95** [comment]
Possibly, although I think there is a danger in having too many configuration files scattered around the file structure that it becomes difficult to find where things are. It's not hugely more complicated to edit the source file then it would be to edit a similar plaintext list.

An alternative would be to have a separate py file within the /r folder which just contains the function dictionaries, I'm open to persuasion/suggestions though.

**Comment by kendonB** [comment]
It's not more complicated to edit the source file, but it is bad style and may prevent users from being able to update with future changes from the repo without awkward merges.

I think that a separate .py file is a good idea, but that the user should be able to copy and paste that to another file in `/user/rules` (or somewhere similar like `/user/dictionaries`) and it would overwrite the first one when the user folder gets sourced. Will that work?

**Comment by kendonB** [comment]
The user might also want to remove items from the dictionaries in case they run into performance issues or complexity limits.

**Comment by mrob95** [comment]
I have made a start on this with #365 , examples of how I'm using this can be seen at:
* https://github.com/mrob95/caster/blob/main/caster/ccr/r/r2.py 
* https://github.com/mrob95/caster/blob/main/caster/ccr/r/r.toml

I'm now basically just adding new command parameters as and when I need them. The Choice_from_file command can load from multiple locations, so it would be feasible to have two toml files: defaults in caster space and an additional one in user space.
