### ISSUE TITLE
User folder disappeared

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/caster#383]
What is the correct way to set user-specific commands now? Just edit the source in the main code?

**Comment by LexiconCode** [comment]
Editing the source code is not ideal as it won't survive updates and isn't standard practice. The user folder is now located `C:\Users\%USERNAME%\.caster\`

To change rules that are prebuilt in the caster utilize [How to Add and Modify Rules](https://github.com/dictation-toolbox/caster/blob/develop/castervoice/doc/readthedocs/CCR.md#how-to-add-and-modify-rules). In addition you should be able to add your own new files in the user directory as well.

The documentation needs to be updated but the principal still apply.

**Comment by LexiconCode** [comment]
Examples of custom rules.
Don't forget to update the imports to caservoice
[scen4.py](https://github.com/dictation-toolbox/caster/blob/master/caster/user/filters/examples/scen4.py)
[modkeysup.py](https://github.com/dictation-toolbox/caster/blob/master/caster/user/filters/examples/modkeysup.py)

The documentation will be updated in the future for more much clearer and cleaner approach to this process. For now it's a bit of an awkward stage Caster development. The take a bit of time but were getting there.

**Comment by LexiconCode** [comment]
In a broader context this issues been discussed in https://github.com/dictation-toolbox/caster/issues/382. Your input would be welcome.
