### ISSUE TITLE
Legion command is nonfunctional after Caster v 0.5.7 and to current release.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#387]
Reproduce issue on Windows 10 64-bit

1. Start Dragon
2. Say the the `legion` command

Expected results
- boxes appear around text

Actual results
- The command is recognized
- The Legion command fails silently with no error message.
- The Legion dll is not terminated properly.

For reference
Legion DPI fix #223
LoadLibrary path fix #222
Legion Enhancement, Cheat sheet update, and more #220

**Comment by LexiconCode** [comment]
I believe that was broken by Windows 10 update.

**Comment by kendonB** [comment]
This seems to work at the moment for me on my Windows 10 machine. Can I close?

**Comment by LexiconCode** [comment]
Test in the morning if it works for on my end.

**Comment by seekM** [comment]
Doesn't work for me:
```
action: Exception from function mouse_alternates:
Traceback (most recent call last):
  File "C:\dev\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "C:\dev\Natlink-User\Caster\castervoice\lib\navigation.py", line 66, in mouse_alternates
    ls = LegionScanner()
  File "C:\dev\Natlink-User\Caster\castervoice\asynch\mouse\legion.py", line 161, in __init__
    self.setup_dll()
  File "C:\dev\Natlink-User\Caster\castervoice\asynch\mouse\legion.py", line 171, in setup_dll
    sys.getfilesystemencoding()))
  File "C:\dev\Python27\Lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\dev\Python27\Lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
action.exec: Execution failed: Function(mouse_alternates): [Error 126] The specified module could not be found
Activate Legion
```

**Comment by LexiconCode** [comment]
> 
> 
> Doesn't work for me:
> 

 To fix `ERROR:action.exec:Execution failed: Function(mouse_alternates): [Error 126] The specified module could not be found`.  Install [Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 (x86).](https://www.microsoft.com/en-us/download/details.aspx?id=40784)

**Comment by seekM** [comment]
>  Install Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 (x86).

Thanks, this did the trick for me. `legion` command is recognized, boxes appear around text. However, further command aren't recognized. I probably experience #500?

**Comment by kendonB** [comment]
I'm back on my Windows 7 computer and I now find that the "Legion" command does nothing...

**Comment by LexiconCode** [comment]
Out of curiosity what is your screen resolution and DPI?

**Comment by kendonB** [comment]
![image](https://user-images.githubusercontent.com/5327505/57589947-4412fb80-757c-11e9-8aa6-4c3b093eebb3.png)

**Comment by kendonB** [comment]
![image](https://user-images.githubusercontent.com/5327505/57589958-53924480-757c-11e9-882d-dad15c9fcbf1.png)

**Comment by kendonB** [comment]
I have changed my VirtualBox displays to be full-screen so that they are both 1920 x 1080. The Legion command still does nothing

**Comment by LexiconCode** [comment]
I realized I don't actually have Redistributable Packages for Visual Studio 2013 (x86) Installed. Although I have a number of other "Redistributable Packages for Visual Studio" installed. Technically I should be receiving ` The specified module could not be found` but it fails silently. Therefore I think the Legion command is trying to use some other version of Redistributable Packages that may not be fully compatible. 

I've installed  ..Visual Studio 2013 (x86) with no success but I'll try uninstalling all other versions and see if that makes a difference.

**Comment by LexiconCode** [comment]
Here's an interesting find. I discovered that I did not have Redistributable Packages for Visual Studio 2013 (x86). nor did it help to install it. So I decided to uninstall all versions of Redistributable Packages for Visual Studio then restart the computer and test.

Even with all Redistributable Packages for Visual Studio removed I still get the behavior described in the op when I should be receiving "ERROR:action.exec:Execution failed: Function(mouse_alternates): [Error 126] The specified module could not be found"

**Comment by kendonB** [comment]
I'm installing Caster on a fresh Windows 10 Virtualbox, right next to my Windows 7 virtual box. I now have Legion working great, after installing the 2013 visual studio redistributable packages. Googlers should note well that this is a different package to that some people require to get Natlink working, despite the naming conventions of the files themselves being the same.

**Comment by LexiconCode** [comment]
I will close issue given that is working for everybody else.

**Comment by kendonB** [comment]
At some point I will experiment with removing the VS packages on my win7 computer and seeing which (if any) is breaking it.

**Comment by kendonB** [comment]
@seekM you mentioned legion isn't working for you again. Can you try uninstalling all your Visual C++ packages and then reinstalling `Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 (x86)`?

**Comment by LexiconCode** [comment]
I ended up ended up reformatting my desktop and I no longer have issues.
