### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by stardobas** [dictation-toolbox/caster#390]
sorry, can I install on python3.7 directly? I don't want install python 2.x ....

**Comment by LexiconCode** [comment]
I can understand that. Fortunately you can run 3.7 and 2.7 side by side. Castor depends upon Natlink which is 2.7.X When Natlink is ported to Python 3. Caster should be quickly converted over along with dragonfly.

**Comment by LexiconCode** [comment]
If you set your python3 sys path Caster will automatic utilize 2.7 interpreter. That way you can use Python 3 as you normally would.
