### ISSUE TITLE
VSCode not picking up dictations

### ISSUE THREAD

**Issue by davidpanaho** [dictation-toolbox/caster#404]
Apologies in advance if this isn't the best forum for troubleshooting. I'm trying to get caster grammars to work with vscode but they're not being written into the workspace. I'm currently using:

- Dragon NaturallySpeaking 13
- NatLink
- Dragonfly
- Caster
- Windows 10

When using Dragon's default voice recognition, the text appears in the workspace. But when I try to use the caster commands, nothing comes up.

This seems to be a recent issue as I was successfully using voice commands in vscode a few months back. Initially, I thought it was the version of vscode but I've reverted back as far as 1.21 to no avail. I've also tried the insiders edition without success.

I'm able to use the voice commands in Sublime Text so I wonder if there's a setting in vscode that I need to enable to make this work.

I'm pretty far out of my depth at the moment so any pointers would be greatly appreciated. Also, if there's a better place for posting troubleshooting questions, I'll be happy to use it instead. Thanks!

**Comment by LexiconCode** [comment]
Welcome David! I will take a look with the latest commit.

If you would like to connect [Discord](https://discord.gg/9eAAsCJ) I could help you with anything else that you need additionally for about an hour.

**Comment by davidpanaho** [comment]
Thank you! that would be wonderful

**Comment by davidpanaho** [comment]
After speaking with @LexiconCode, he was able to debug/fix the issue so I'm putting this up for anyone else who runs into the same problem.

I was launching vscode from a terminal window with elevated privileges, which prevented the Dragonfly commands from running. At this stage you can't run vscode with elevated privileges (Administrator mode) if you want to use Dragonfly.
