### ISSUE TITLE
ReadTheDocs is broken

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#431]
**From @kendonB: WHILE RTD IS BROKEN, PLEASE VIEW THE DOCS DIRECTLY IN GITHUB: https://github.com/dictation-toolbox/Caster/tree/develop/castervoice/doc**

The ReadTheDocs is using the old repository and has not been updated for dictation-toolbox. @synkarius will need to be contacted for migration.

In addition
https://readthedocs.org/projects/caster/builds/
The last build (3 months ago) failed because it tried to compile wxWidgets.

**Comment by kendonB** [comment]
Putting this here for reference https://docs.readthedocs.io/en/latest/builds.html

I'm trying to fix this

**Comment by kendonB** [comment]
The site is broken: https://caster.readthedocs.io/en/latest/

The original issue was that mkdocs was enforcing that the site build directory not be within the site doc/ source directory.

I added a mkdocs.yml file specifying site_dir and docs_dir following https://www.mkdocs.org/user-guide/configuration/.

Then the build succeeded but lots of the pages showed 404 not found. This is still the case now.

I tried adding the `pages` (`nav` in the docs doesn't work but `nav`~`pages`) variable for a single md file and it also didn't work.

Build info is here:
https://readthedocs.org/projects/caster/builds/

@LexiconCode @synkarius I would like some help to figure out what's preventing the site from building please!

**Comment by kendonB** [comment]
Asked on RTD https://github.com/rtfd/readthedocs.org/issues/5756

**Comment by LexiconCode** [comment]
Make an account on RTD and I will add you as a maintainer.

**Comment by kendonB** [comment]
I made the account on RTD so I'm ready for you to make me a maintainer.

**Comment by LexiconCode** [comment]
@kendonB Done

**Comment by kendonB** [comment]
Made some progress. It builds fine here in my version: https://kendonbcaster.readthedocs.io/en/latest/ but is still failing and I can't see what's different. I asked for help here: https://github.com/rtfd/readthedocs.org/issues/5761

**Comment by kendonB** [comment]
Fixed now.

**Comment by nrmh** [comment]
ReadMe.md links to https://caster.readthedocs.io/en/latest/README/, which doesn't work. https://caster.readthedocs.io/en/latest/ works fine, though.

**Comment by LexiconCode** [comment]
> 
> 
> ReadMe.md links to [caster.readthedocs.io/en/latest/README](https://caster.readthedocs.io/en/latest/README/), which doesn't work. [caster.readthedocs.io/en/latest](https://caster.readthedocs.io/en/latest/) works fine, though.

Thank you. Links Fixed

**Comment by nrmh** [comment]
Just noticed there's a few other links to the docs, all are broken in a different way. `s/latest\/caster\/doc/latest/` should fix them.

**Comment by LexiconCode** [comment]
Good to know I'll see if I can fix it this weekend or earlier if time allows
