### ISSUE TITLE
Using "kick" after sikuli click follows the 

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#446]
To reproduce, click an object using sikuli, then say "kick" when the cursor is somewhere else. The click event will happen at the sikuli location, not the cursor location.

**Comment by LexiconCode** [comment]
Does it occur once after or isnit reoccurring at the sikuli location?

**Comment by kendonB** [comment]
If I say kick many times, the click events will all occur at the sikuli location. Does that answer your question?

**Comment by LexiconCode** [comment]
Yes it does clarify the situation.

**Comment by LexiconCode** [comment]
which version of sikuli and caster?

**Comment by kendonB** [comment]
caster https://github.com/dictation-toolbox/Caster/commit/0c2ea0da11d5115f7b9d60e247c0804a2054678c

sikuli 1.1.4

**Comment by LexiconCode** [comment]
I'm unable to reproduce this error. 
[click.sikuli.zip](https://github.com/dictation-toolbox/Caster/files/3069954/click.sikuli.zip)

Is there anymore relevant information you think you could provide?

**Comment by kendonB** [comment]
Interesting. I don't think there's anything else. Can you think of something else that might be different between our systems? I'm on a Windows 7 Virtualbox guest on a Ubuntu 18.04 machine.

**Comment by LexiconCode** [comment]
I've tried to reproduce this on to my machines. So I've laid out my testing procedure to make sure were on the same page.

1. Creating Sikulix script of a (shortcut one). 
2. Then's executing Sikulix script successfully clicking on (shortcut one) . 
3. Moving the mouse away and saying `kick` on another icon (shortcut two) . 

Result `kick` clicks on the (shortcut two) expected versus (shortcut one) from the Sikulix script.

**Comment by kendonB** [comment]
I am travelling away from that computer at the moment so will get back to you on this in about 3 weeks.

**Comment by kendonB** [comment]
I am unable to reproduce this on a second machine. The other one is Windows 7 and this one is Windows 10 - that may be why.

**Comment by LexiconCode** [comment]
That's good to know, I am using Windows 10 as well.  That being said I don't have access to a Windows 7 environment for testing.

**Comment by kendonB** [comment]
I've solved this issue by removing mouse integration via the "Devices" menu in virtual box. ref: #507
