### ISSUE TITLE
Image file missing in documentation

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#460]
https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/doc/readthedocs/Taxonomy_of_a_Rule.md references https://github.com/dictation-toolbox/Caster/raw/develop/caster/doc/img/terminology.png which is not avaiable.

**Comment by seekM** [comment]
I found the image at caster/doc/img/terminology.png. I could do a PR but I'm not sure if one should reference the image via absolute path (master or develop branch?) or via relative path.

**Comment by LexiconCode** [comment]
Good catch!

A pull request for the development branch with an absolute path. Eventually the readme will be bundled into the read the docs which will eliminate the issues with URL paths and document versioning for master/development.

**Comment by LexiconCode** [comment]
It's fixed, thanks again!
