### ISSUE TITLE
Sikuli doesn't work after switching between profiles

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#463]
Steps to reproduce:
- Create two user profiles A and B
- Define a simple Sikuli command, e.g. an *export_window* function in *test.sikuli* which clicks on the windows symbol bottom left
- Start Dragon, select profile A. The *test window* command works
- Terminate Dragon
- Start Dragon, select profile B. The *test window* command works
- Terminate Dragon
- Start Dragon, select either profile A or B. As before the *test window* command works. Switch the user profile from A to B or B to A respectively. 
Now the *test window* command isn't recognized anymore. I expected it to work.
No errors are shown in the Natlink or Sikuli Server window.

Use case: I'd like to use Sikuli commands to switch easily between a German and an English profile.

Do you think the problem is to be located within Sikuli or Caster?

Specs:
Sikuli 1.4
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by LexiconCode** [comment]
Are you also closing the Sikuli server between profiles?

**Comment by seekM** [comment]
No, I leave everything as it is, including Sikuli server and Natlink window

**Comment by LexiconCode** [comment]
try closing Dragon between switching profiles including including Sikuli. The Natlink window should automatically close with Dragon.

**Comment by seekM** [comment]
Not sure I understand - if I close Dragon the Natlink window is closed as well. I can also close the Sikuli window. If I then start Dragon again and select the other profile everything works fine as said above. But I want keep Dragon running and use Sikuli to switch between profiles by voice (Profile -> Open Recent User Profile -> ...)

**Comment by LexiconCode** [comment]
> Not sure I understand - if I close Dragon the Natlink window is closed as well. I can also close the Sikuli window. If I then start Dragon again and select the other profile everything works fine as said above. But I want keep Dragon running and use Sikuli to switch between profiles by voice (Profile -> Open Recent User Profile -> ...)

I didn't catch it the first time around. That is clarifying. So none of the following commands work as well as Sikuli commands?

```
        "launch sick IDE": Function(launch_IDE),
        "launch sick server": Function(launch_server),
        "refresh sick you Lee": Function(refresh_sick_command),
```
