### ISSUE TITLE
Sikuli's control commands aren't recognized

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#468]
I can call custom Sikuli scripts by voice. However, [these](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/asynch/sikuli/sikuli.py#L107-L112) standard control commands aren't recognized when I say them. Can someone confirm?

**Comment by LexiconCode** [comment]
I can confirm. @kendonB?

**Comment by kendonB** [comment]
Yes I can confirm that these didn't work a few weeks ago when I was first trying sikuli.

**Comment by seekM** [comment]
I'm working on a fix
