### ISSUE TITLE
WXPYTHON_PATH and PYTHONW aren't set correctly

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#486]
For me they were set to `C:/Python27/Lib/site-packages/wx-3.0-msw` resp. `C:/Python27/pythonw` in `caster\data\settings.toml`. However, I installed Python at `C:/dev/Python27` and had to adjust the pathes manually. I noticed this when I tried to use the `rainbow` and `douglas` commands which didn't work because of this. I think the correct pathes should to be configured automatically or alternatively the user should be notified that he has to modify the pathes manually.

**Comment by LexiconCode** [comment]
Related to #346
