### ISSUE TITLE
Helper function to checkout a branch on github from a web browser

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#494]
Just thinking about ways to do this

One can fetch using e.g.:
```
git fetch https://github.com/dictation-toolbox/Caster.git pull/490/head
```
which puts the new branch into FETCH_HEAD. Then we can check it out as a new branch like:
```
git checkout -b dictation-toolbox/Caster/pull/490 FETCH_HEAD
```
Then you're done! So, the process would be (from a PR main page):

- Ctrl-L to go to the address bar
- Copy to a python object (The string is of the form: `BASEURL/pull/PULLID`)
- Do a string split by `/pull/`.
- Open git bash
- How will it know where your local repo is? SOLVED
- Take the first element of the string split and do: 
```
git fetch <str_split1>.git pull/<str_split2>/head
```
- Do a string replace with <str_split1> replacing `"https://github.com/"` with ""
- Then:
```
git checkout -b <str_split1> FETCH_HEAD
```

**Comment by kendonB** [comment]
What's the best way to do this within caster? Another function in `utilities.py`?

**Comment by kendonB** [comment]
Perhaps .caster could have a toml matching BASEURL to user folders

**Comment by LexiconCode** [comment]
That would be tricky

>     * How will it know where your local repo is? NEED HELP ON THIS STEP

The install folder for the classic install is the local repo. If I'm understanding your definition of local repo and not the remote.

**Comment by kendonB** [comment]
> The install folder for the classic install is the local repo. If I'm understanding your definition of local repo and not the remote.

Not sure what you mean by this. To be clear, this feature would work for any github repository for which the user has a local copy. I believe my idea of having a .toml of BASEURLs and user folders would work to link the copied URL to the local folder.

**Comment by kendonB** [comment]
How does one copy a selection to a python object within caster? I want to do something like `new_object = navigation.stoosh_keep_clipboard()`

**Comment by kendonB** [comment]
alexboche: `lib.context.read_selected_without_altering_clipboard`

**Comment by kendonB** [comment]
I have made a start but haven't been able to get `Key` to work to get dragonfly/caster to type "Ctrl-L" to move to the address bar of the browser. How do I do this from within a function? I have it imported using `from castervoice.lib.actions import Key` and I'm just invoking it using `Key("c-l/20")`.

**Comment by LexiconCode** [comment]
You could do Key("c-l/20"). execute()

**Comment by kendonB** [comment]
This is almost done in #498. Closing here.
