### ISSUE TITLE
Remove Click-By-Voice chrome helper functions in chrome.py

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#495]
I have had problems getting these to work reliably. Clicking/hovering etc just doesn't work.

@Versatilus also had to comment them out:
> I didn't notice any configuration options for that so I had to make a branch and comment those lines out just to handle the issue for myself. They are just too sensitive for me.

Does anyone use Click by Voice with success? If so, do you know what you did to get it to work?
I think that if we keep these, they should go to another grammar that's disabled by default, though I'm not sure if we're able to have App grammars that we can enable and disable?

Any thoughts?

**Comment by kendonB** [comment]
From @alexboche:
> Click by voice seems to be working a little bit inconsistently in Gmail for me. Note that the click by voice extension actually does not relate to voice directly. The commands I wrote for it just press control shift space and then type in the number into the little box that appears on the top right optionally followed by a colon and an option for stuff like opening the link in a new tab, so the problem may be something about the pause time which you could fiddle around with. If it's not working, you might try making some vocola or Advanced Scripting commands for this. Also I noticed that sometimes you have to say one hundred seventy five instead of one seventy five, especially if you're not using one of the options e.g. for opening a new tab. Voice computer and speech start are other options for numbering software. Personally I switched to Outlook once I started using Dragon since everything is full text control.

I can't even get the CBV plugin to respond to Ctrl-Shift-Space using the actual keyboard on my machine. It doesn't seem like a reliable plugin. 

Legion/Rainbow are a little slow, but they currently work AFAIK, so I don't see a need for CBV to also be supported by default given 1) it doesn't seem to be stable (even without voice), 2) it requires the user to know to install the extension, and 3) it introduces buggy behavior if the extension is not installed.

**Comment by LexiconCode** [comment]
I would agree removing CBV. We should keep a copy of the commands though gist.

**Comment by kendonB** [comment]
https://gist.github.com/kendonB/2ae813d01c1d90c93ae8d0e818791b6a
