### ISSUE TITLE
Consider removing space in "insert commandnoarg"?

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#503]
@mrob95 ,  @alexroche, do you find it more annoying to remove spaces that you don't want or to add spaces when you want them when using "insert \<commandnoarg\>"? Any other LaTeX users should also weigh in.

**Comment by alexboche** [comment]
In general I think I would prefer removing spaces that I don't want to adding spaces, but I don't have much experience using pure latex so my preference is not specific to this.

**Comment by kendonB** [comment]
We will leave the space in.
