### ISSUE TITLE
GitBash grammar: @ and { not working in mingw64 terminal

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#504]
I'm using [Git for Windows](https://gitforwindows.org/) and the "Git Bash here" option from the context menue inside Windows Explorer which opens a ming64 terminal. When I try to use the [git stash spec](https://github.com/dictation-toolbox/Caster/blob/c5074e2a8b7de348cbfa80a4686e7e2d5db2ed9a/caster/apps/gitbash.py#L98-L99) I expect `git stash apply stash@{n}` to be printed. However, some text appears and is removed, in the end only `1p` is outputted. Similarly, commands like `atty` and `curly` don't work in the mingw64 terminal, nothing is printed when I say them.

**Comment by LexiconCode** [comment]
These commands work for me
> `atty` and `curly`
> `git stash apply stash@{n}`

git stash apply 5 -> git stash applystash@{5}
