### ISSUE TITLE
"duple" working inconsistently

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#505]
Just started noticing this today. Sometimes it will work fine and sometimes it will paste something else that was on the clipboard. Anyone else seen this problem?

**Comment by LexiconCode** [comment]
I'm not able to reproduce the issue. However the clipboard has been finicky in the past so here's the related function.
```Python

def duple_keep_clipboard(nnavi50):
    cb = Clipboard(from_system=True)
    Key("escape, home, s-end, c-c, end").execute()
    time.sleep(settings.SETTINGS["miscellaneous"]["keypress_wait"]/1000.)
    for i in range(0, nnavi50):
        Key("enter, c-v").execute()
        time.sleep(settings.SETTINGS["miscellaneous"]["keypress_wait"]/1000.)
    cb.copy_to_system()
```

**Comment by kendonB** [comment]
This was an issue with my Windows 7 set up (with lots and lots of VS packages) but doesn't seem to be an issue on either of my Win 10 machines. Will close for now.
