### ISSUE TITLE
words.txt doesn't work for alphabet

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#506]
This `words.txt`

```
<<<NOT_SPECS>>>
brov -> bat
```

doesn't have an effect for me.

If I replace [this line](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/ccr/core/alphabet.py#L18) with the explicit 

```
        Choice("letter", {
            "arch"    : "a",
            "brov"    : "b",
            "char"    : "c",
            "delta"   : "d",
            "echo"    : "e",
            "foxy"    : "f",
            "goof"    : "g",
            "hotel"   : "h",
            "India"   : "i",
            "julia"   : "j",
            "kilo"    : "k",
            "Lima"    : "l",
            "Mike"    : "m",
            "Novakeen": "n",
            "oscar"   : "o",
            "prime"   : "p",
            "Quebec"  : "q",
            "Romeo"   : "r",
            "Sierra"  : "s",
            "tango"   : "t",
            "uniform" : "u",
            "victor"  : "v",
            "whiskey" : "w",
            "x-ray"   : "x",
            "yankee"  : "y",
            "Zulu"    : "z",
        }),
```

the sample `words.txt` above has the desired effect.

Can someone confirm?

**Comment by seekM** [comment]
This was confirmed by another user in the gitter chat.

Does anyone have an idea how this can be fixed? Copying the Choice-alphabet stuff to all places isn't the right solution I guess?

**Comment by LexiconCode** [comment]
I think it's because of how it's loaded in Alphabet(MergeRule): as an import maybe?

**Comment by LexiconCode** [comment]
> This was confirmed by another user in the gitter chat.
> 
> Does anyone have an idea how this can be fixed? Copying the Choice-alphabet stuff to all places isn't the right solution I guess? I think it's important that people can change the alphabet using words.txt

I can't reproduce the stated issue using `brov -> buck`. Can you confirm that this is still an issue for you @seekM?
