### ISSUE TITLE
Make bow/bowel optional

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#510]
I have done this for a long time and my own version of caster, but it's not an option to make it optional in the current version. I haven't noticed any unusual behavior since making it optional.

Is there a pitfall I'm missing?

**Comment by LexiconCode** [comment]
That's a good point and I'm not aware of one. Although I haven't implemented it personally. This would be a good thing to bring up in the gitter for feedback from a wider audience.

**Comment by kendonB** [comment]
There was a least one response from someone who said making this optional works fine for them. There were also no objections that I saw. @LexiconCode , can I go head make this change?

**Comment by LexiconCode** [comment]
Sure

**Comment by kendonB** [comment]
Done: https://github.com/dictation-toolbox/Caster/pull/550
