### ISSUE TITLE
Inconsistent behaviour with carrot

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#512]
[Carrot](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/lib/ccr/core/punctuation.py#L63-L64):
```
 "carrot":
    R(Text("^"), rdescript="Core: Carat"),
```

I'm getting inconsistent behaviour using carrot. I was just trying it and saying `carrot` yields nothing, saying it again yields `^^`. Yesterday saying `carrot` gave me `^^` directly on the first try. Expected behaviour: Say it once, get `^`. I tried it in Notepad++. Anyone else experiencing this?

**Comment by kendonB** [comment]
No unusual behavior here. Are you using an unusual keyboard? On my Māori keyboard, we prefix with the backtick to add macrons, for example, which introduces unusual behavior if you're actually trying to make a backtick.

**Comment by kendonB** [comment]
Is there another carrot command somewhere deep in your vision of caster? try find in files?

**Comment by seekM** [comment]
I fiddled with Window 10 language and keyboard settings and figured this out:

German language, German keyboard: `^^`
German language, English US keyboard: backtick (can't format it here)
English language, German keyboard: `&`
English language, English US keyboard: `^`

**Comment by seekM** [comment]
For Windows 10 German language, German keyboard layout I could fix it using this `rule filter`:
```
def update_carrot(rule):
    if "carrot" in rule.mapping_actual().keys():
        rule.mapping_actual()["carrot"] = R(Key("caret") + Key("left") + Key("delete"))

def fix_carrot_german_windows10_scenario(mp):
    if mp.time == MergeInf.BOOT:
        if mp.rule1 is not None :
            update_carrot(mp.rule1)   
        update_carrot(mp.rule2)
```
That these modifications might be needed depending on which language / keyboard layout you have should probably be added to the documentaion?

**Comment by kendonB** [comment]
Can we detect the keyboard and language within caster and fix up the output? Long term it would be a shame if we only supported the English / English combo.

**Comment by LexiconCode** [comment]
Yes we do need to handle alternate keyboards better. Fundamentally though is this something that's a caster issue or dragonfly?

**Comment by kendonB** [comment]
A KeyboardLanguageContext class from dragonfly would be great. People do change these on the fly (at least I do) so we'd want to detect last second like AppContext

**Comment by kendonB** [comment]
Will close this for now while we wait and see what comes from Dragonfly
