### ISSUE TITLE
Refactor apps grammars to have standard grammar

### ISSUE THREAD

**Issue by lexxish** [dictation-toolbox/Caster#520]
Similar to how we have a standard for CCRs (https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/lib/ccr/standard.py), we need to create a similar standard for applications. The different domains of applications would be for example IDE, Browser, WordProcessor, and each implementation would have standard grammar in common. For example, both Chrome and Firefox would be implementations of the browser grammar and they would both contain "back", "forward", etc.

**Comment by LexiconCode** [comment]
I'm in favor of this as it simplifies documentation and makes it easier to utilize filter rules. However this will change the command names across all application grammars which would be disruptive to the community.

**Comment by kendonB** [comment]
I think we should make a call on whether we do this after assessing the extent to which there actually is conflict across apps. I believe that there's not that much conflict

**Comment by lexxish** [comment]
If there ends up being too many conflicts it could be implemented as a refactoring. That's what I intended initially anyway, but a rewrite would be much cleaner and better long-term.

**Comment by kendonB** [comment]
`ContextAction` is very compact: https://github.com/dictation-toolbox/Caster/pull/493/files

Let's consider whether we should even have the standard elements redefined within App Grammars or if they should all be done using `ContextAction`s. I think it would be much tidier to pull all of the common stuff out of the app grammars and just use those for app-specific commands.

**Comment by kendonB** [comment]
The only downside I see is that it makes it a little less transparent to new users how to add a new app. Since that's relatively rare, I still think it's the right way to go.

**Comment by LexiconCode** [comment]
Work in progress but the initial commit is done we will open up other issues as we convert.
