### ISSUE TITLE
Unified reboot implementation.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#522]
Currently caster supports WSR for DNS for speech recognition backends. Currently these exist as two separate commands to reboot the engines. A unified approach would be a lot simpler from the end-user's perspective and needed as more back ends are added to dragonfly.

The spec could be "reboot caster"
Perhaps we could conditionally call the reboot bat/scripts by checking which engine is loaded in dragonfly.

**Comment by lexxish** [comment]
I'd also like to see automatically open a default Dragon profile and automatically turn on the microphone.

**Comment by LexiconCode** [comment]
Sure I believe I can implement that.

**Comment by lexxish** [comment]
Lastly sometimes Dragon NaturallySpeaking completely locks up. Can you also make the reboot accessible via a shortcut (e.g. taskbar shortcut)? This might be a little harder… Not sure

**Comment by LexiconCode** [comment]
> 
> 
> Lastly sometimes Dragon NaturallySpeaking completely locks up. Can you also make the reboot accessible via a shortcut (e.g. taskbar shortcut)? This might be a little harder… Not sure

I have a shortcut to the bat "castervoice\bin\reboot.bat"

**Comment by kendonB** [comment]
> Lastly sometimes Dragon NaturallySpeaking completely locks up. Can you also make the reboot accessible via a shortcut (e.g. taskbar shortcut)? This might be a little harder… Not sure

I ended up making my own `.bat` to solve this problem before knowing where to find the stock one. Might be worth adding this to the desktop automatically? Though that might be a bit paternalistic. Once we get to having a `.exe` installer we could make it optional.

**Comment by LexiconCode** [comment]
Partially implemented by reboot to same user profile.
https://github.com/dictation-toolbox/Caster/pull/574

**Comment by LexiconCode** [comment]
Unified reboot is implemented in https://github.com/dictation-toolbox/Caster/commit/69d10d8bcc7a5a4e3168e496599dd70050dc99e5

Toggling microphone state on and off will be added in the future.
