### ISSUE TITLE
macro "times" command to repeat macros doesn't work

### ISSUE THREAD

**Issue by lexxish** [dictation-toolbox/Caster#526]
The command is logged properly as `Recorded Macro: macro [times <n>]` but macro only runs once.

**Comment by LexiconCode** [comment]
I can reproduce this behavior

**Comment by lexxish** [comment]
@LexiconCode any idea what's wrong here? I will definitely want to leverage this functionality for other issues I'm working on. I looked at it but didn't see anything obvious

**Comment by seekM** [comment]
It doesn't work for me as well. I found the [times <n> spec](https://github.com/dictation-toolbox/Caster/blob/c5074e2a8b7de348cbfa80a4686e7e2d5db2ed9a/caster/lib/ccr/recording/history.py#L63), but not where it's functionality is implemented, any idea?

**Comment by mrob95** [comment]
Try altering this line:
https://github.com/dictation-toolbox/Caster/blob/c5074e2a8b7de348cbfa80a4686e7e2d5db2ed9a/caster/lib/ccr/recording/history.py#L83

So that it looks like:
```
R(Playback(), rdescript="")*Repeat(extra="n")
```

I don't have time to test it at the moment but if it works the way I think it does then that should fix it.

**Comment by seekM** [comment]
Thank you, this did the trick for me!

**Comment by LexiconCode** [comment]
@lexxish fixed!
