### ISSUE TITLE
File Explorer doesn't always appear in foreground

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#527]
When I call "bring me X folder" often the Windows Explorer / File Explorer instance does not appear in the foreground. Is there a way we can get this to happen more consistently?

**Comment by LexiconCode** [comment]
I can't reproduce this. Is there anything stealing focus?

**Comment by kendonB** [comment]
I think this has basically stopped happening after I reset the registry key using what was suggested here: https://github.com/dictation-toolbox/Caster/issues/194 This is on my Windows 10 machine. I will close for now. However, requiring users to reset a registry key should be something that we try to overcome in a better way at some point.
