### ISSUE TITLE
"website/folder to bring me as <key>" doesn't seem to be working

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#528]
The command gets recognized but nothing seems to appear in the toml file.

**Comment by kendonB** [comment]
Scratch that, it seems to work sometimes but not others. For example when I try to add the pull requests page as "caster pull requests", nothing shows up (after many tries) whereas if I try to add individual pull requests, it always seems to work.

**Comment by LexiconCode** [comment]
I'll see if I can reproduce this on my side as well.

**Comment by kendonB** [comment]
Eventually it worked. Maybe there needs to be a pause increased.

**Comment by kendonB** [comment]
I will close this for now as it seems to be working usually
