### ISSUE TITLE
Add terminal folders to bring me

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#529]
In #498, I add a "TERMINAL_PATH" settings variable to help with opening a terminal using git bash then navigate to a folder.

This first action could well be desirable in many circumstances. I propose adding a "terminal" list inside the `bringme.toml` that will open the folders listed there in the user's terminal.

**Comment by LexiconCode** [comment]
This is now implemented correct? @kendonB

**Comment by kendonB** [comment]
On it's way. Will close once it's merged https://github.com/dictation-toolbox/Caster/pull/614

**Comment by kendonB** [comment]
This use case is covered by this comment and is not yet implemented https://github.com/dictation-toolbox/Caster/pull/614#issuecomment-506991300
