### ISSUE TITLE
Caster fails on startup with SystemError: Your platform is not currently supported by Caster

### ISSUE THREAD

**Issue by rakeshnbabu** [dictation-toolbox/Caster#536]
Hello,

After commit 2266132, caster fails to start with error message "Your platform is not currently supported by Caster". Caster was working correctly before this commit.

I'm running Caster and dragonfly on python 2.7 with Anaconda3 on Windows 10.

**Comment by rakeshnbabu** [comment]
it seems this was my fault. i have 64-bit python 2.7 installed, and the documentation calls for 32 bit. is there any technical reason to exclude 64-bit python?

**Comment by kendonB** [comment]
Were you running python x64 before and everything was working?

**Comment by rakeshnbabu** [comment]
yes.  actually, to the point that i had no idea that i screwed up!

**Comment by kendonB** [comment]
From Natlink:

> Warning: Natlink does not work when you install a "64 bit" python version. So DO NOT USE the Windows x86-64 MSI installer.

This may no longer be true.

**Comment by rakeshnbabu** [comment]
i'm using windows speech recognition until my order for dragon comes in, so that might be the difference.

**Comment by kendonB** [comment]
I will contact the Natlink authors and see what's up and whether this still needs to be 32 bit python.

**Comment by kendonB** [comment]
Ah I see. So no Natlink at all.

**Comment by kendonB** [comment]
So it is a bug in the requirements checking as we should allow 64 bit python + WSR.

**Comment by LexiconCode** [comment]
I would be hesitant to include 64-bit Python for WSR.  Most people moved to DNS after working with WSR which would necessitate uninstalling Python 64-bit and installing the 32-bit version. @kendonB natlink state otherwise we can can change requirements to 64-bit for both DNS and Dragon.
