### ISSUE TITLE
RDP mode configurable wait times for dragonfly key modifiers

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#539]
Reported in Gitter by @rakeshnbabu 

> When i work over rdp, it seems that the shift key doesn't engage fast enough. yell case shows up like "as cAPITALIZATION wORK" and snake spacing shows up as "this-is-an-example-of-snake-case"
> is there a setting that i need to tweak somewhere?

Suggested solution by @SwellGuy88_twitter 
> The fix for that would be in dragonfly. I had it fixed at one point but don't have that machine anymore. I think I needed to up the wait time between keystrokes in dragonfly. Maybe @Danesprite has thoughts on a permanent fix. Maybe they could respect our RDP mode flag or just increase it globally.

**Comment by Danesprite** [comment]
You can adjust the default pause time for `Key` through the `interval_factor`and/or `interval_default` attributes. I'm not sure if this affects `Text` too, but the default pause time for it can be adjusted by through the `_pause_default` attribute.

Given that this only seems to effect RDP mode, perhaps sub-classes could be used only if that option is enabled? They can be added in `caster.lib.actions` like I did with the Aenea support. A sub-class for `Key` could be done like so:

```Python
from dragonfly import Key as KeyBase

class Key(KeyBase):
    interval_factor = 0.02
    interval_default = 0.01

```

**Comment by chilimangoes** [comment]
@Danesprite Have you made changes to how `interval_factor` and `interval_default` work in Dragonfly since you took over? I remember trying to tweak those to fix the RDP issue a couple of years ago, and it worked, but I ran into issues, especially with needing to basically modify the values and restart Dragon to take effect, which made switching back and forth a pain. Although, I don't think I even thought of subclassing Key, so maybe that's what I was missing.

**Comment by Danesprite** [comment]
@chilimangoes Nope, no changes to how they work. The equivalent `_pause_default` for the `Text` action was changed though.

Subclassing is definitely the way to go for changing these attributes. It would be pretty simple to also do this in an application grammar file if required.

**Comment by chilimangoes** [comment]
Cool, thanks. I recently reinstalled Windows on my laptop and need to get Dragon/Caster running again but will give this a try once I get that out of the way.

**Comment by ethangoldstein** [comment]
So I changed the _pause_default attribute from 0.003 to 0.02 and there was mild improvement when using the Remote Desktop. However, Castor was still not functioning correctly within the Remote Desktop and Castor was very difficult to use while not in the Remote Desktop. I have changed it back to 0.002 for now, but I imagine that the _pause_default attribute can be changed dynamically with the context library. Does this sound about right? I imagine then that I would be able to use pastor within the Remote Desktop.

**Comment by LexiconCode** [comment]
There's a number of ways you can approach this.

One would be to import the settings checking for rdp_mode. Then define the override in similarly to how caster aenea dynamically changes imports for Key, Text, Mouse. See
```
from castervoice.lib import settings
settings.SETTINGS["miscellaneous"]["rdp_mode"]
```
https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/actions.py

**Comment by ethangoldstein** [comment]
hmm, okay. it seems like this issue is much larger than this specific use case. do you think it would be possible to load the parameters require into a variable located outside of the key, text. and mouse libraries and have caster reference the variables?

**Comment by mrob95** [comment]
I haven't had a chance to test it, but something like this may work in `lib/actions.py`:

```
from dragonfly import ContextAction
from dragonfly import FuncContext
from dragonfly import Text as TextBase
from dragonfly import Key as KeyBase

from castervoice.lib import settings

class SlowText(TextBase):
    _pause_default = 0.02

class SlowKey(KeyBase):
    interval_default = 1.0

rdp_context = FuncContext(lambda: settings.SETTINGS["miscellaneous"]["rdp_mode"])

def Key(*args, **kwargs):
    return ContextAction(KeyBase(*args, **kwargs),
        [(rdp_context, SlowKey(*args, **kwargs))])

def Text(*args, **kwargs):
    return ContextAction(TextBase(*args, **kwargs),
        [(rdp_context, SlowText(*args, **kwargs))])
```

checks for RDP mode before executing any key or text actions, and slows them down if necessary. I don't know whether grabbing settings from file every time will affect performance though.

**Comment by LexiconCode** [comment]
RDP mode has been removed from 1.0.0

**Comment by LexiconCode** [comment]
The timing issue can be resolved without code changes see https://github.com/dictation-toolbox/Caster/issues/707 Using RDP with Caster/Dragonfly
