### ISSUE TITLE
Are the App / CCR language quick references generated automatically?

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#542]
If so, how? If not, how might we?

**Comment by LexiconCode** [comment]
1. Use dragonflys RPC server to pull grammars from the engine once Caster is loaded. The grammars represented in engine should be representative of a what's available for dictation taking into account filter rules, words.txt and manual edits to source code.

This is already been implemented and you can experiment with the following file printing out to the natlike status window.
[configdebug.txt](https://github.com/dictation-toolbox/Caster/files/3219929/configdebug.txt)

> Instructions to use configdebug.txt on the latest version of Caster Development branch.
> 
>     Edit or replace configdebug.txt in C:\Users\%USERNAME%\.caster\data
>     Then say refresh debug file to load the debug grammar.

**note**:after enabling say "generate token" then replace the token in configdebug.txt for security purposes.

2.[pytablewriter](https://github.com/thombashi/pytablewriter) or [PyLaTeX](https://github.com/JelteF/PyLaTeX) to programmatically generate PDF files.
A trim down of a PyLaTeX example.

[PyLaTeX.zip](https://github.com/dictation-toolbox/Caster/files/3220360/PyLaTeX.zip)
We can use [CasterQuickReference.tex](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/doc/CasterQuickReference.tex) as a guide to re-create the structure in PyLaTeX.

Most of the `CasterQuickReference.tex` outside of formatting subsections.
Consists of `\command{Command Name}{printed result}`

We delineated each subsection by grammar name from rpc. Then for each grammar name store in variables the rules in the grammar along with any special formatting for that section like a footer and so forth.

Some groundwork may need to be laid within caster such as consistent grammar names and so forth.

**Comment by kendonB** [comment]
Is it necessary to continue using the .tex file? That approach is nice for printing stuff out on paper but a simple .md is much easier to deal with. Given we have "bring me" now, pulling up an arbitrary doc page is fast and easy ("bring me python docs", for example).

**Comment by LexiconCode** [comment]
> Is it necessary to continue using the .tex file? That approach is nice for printing stuff out on paper but a simple .md is much easier to deal with. Given we have "bring me" now, pulling up an arbitrary doc page is fast and easy ("bring me python docs", for example).

Yes it is much easier to utilize `.md`, However is very limited in terms of actual formatting. Markdown doesn't have no header or footer with notations that help us explain complex commands. In addition `.tex` allows for clean customizable tables. 

All that being said if you can create `.md` documentation that's capable of displaying complex commands and looks decent I would be interested! Then we could try formulating this automation with .md instead.

**Comment by kendonB** [comment]
So footnotes are a bit awkward to code up but are possible:

https://github.com/kendonB/Caster/blob/what_i_use/castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md#myfootnote1

**Comment by LexiconCode** [comment]
It looks like a start ! I'll have to give it a closer look in a couple weeks when I'm finished up with my program. We will have to see if it scales to quick reference versus the application quick reference.

**Comment by LexiconCode** [comment]
closing this in favor of https://github.com/dictation-toolbox/Caster/issues/234
