### ISSUE TITLE
Replace Playbacks by shortcuts

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#544]
Playbacks should be replaced by shortcuts if possible. Shortcuts are language-agnostic most of the time. 

Example:
[This command](https://github.com/dictation-toolbox/Caster/blob/a86443dd5ee80292fe2caced8b8fa392044a7ddc/_caster.py#L98-L99) only works for English DNS. If one used the shortcut for minimizing windows (not sure what it is) it's more likely that it would work for other language versions as well.

**Comment by LexiconCode** [comment]
I agree or even by other means that are platform specific. The reason this was done in the first place as it mimics built-in DNS commands which are not affected by lack of administrator privileges.

**Comment by LexiconCode** [comment]
@mrob95 thoughts on how to proceed with this as it's going to become more of an issue when we utilize other engines not to mention languages. ATM specifically WSR engine.

**Comment by LexiconCode** [comment]
@seekM Done and cross-platform

https://github.com/dictation-toolbox/Caster/commit/d03a1c5a80c7f8b6d930101dbe32e267c80ad558
