### ISSUE TITLE
>= and <= sometimes don't work

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#547]
https://github.com/dictation-toolbox/Caster/blob/401857c2b3024875431e69460364c811c6eecf4b/castervoice/lib/ccr/core/punctuation.py#L25-L28

These are sitting in `punctuation.py` yet they don't seem to work for me. Do they work for anyone? Any idea why they might not?

**Comment by seekM** [comment]
Both work for me

**Comment by kendonB** [comment]
I find that "less equal" and "greater equal" work but not "is greater than or equal to" or "is less than or equal to". Good enough I guess.
