### ISSUE TITLE
windows speech recognition stop listening command does not work

### ISSUE THREAD

**Issue by rakeshnbabu** [dictation-toolbox/Caster#549]
when using the window speech recognition engine, the default command "stop listening" does not cause the speech recognition engine to go to sleep mode.

**Comment by kendonB** [comment]
I don't think this is a caster issue. Please reopen if you disagree.

**Comment by rakeshnbabu** [comment]
I don't think the window speech API is designed to listen for any commands , including its own stop listening command.  I believe that it's up to the downstream applications implementing the API to implement some sort of sleep mode.

**Comment by kendonB** [comment]
I'm still confused as to what we could do. What happens if you say "stop listening" with caster turned off? If it does anything, do you know which module it runs and if that might be accessible to caster?

**Comment by rakeshnbabu** [comment]
I looked into the architecture of how Caster and dragonfly interact, and this might be better placed as a dragonfly bug. 

When caster starts dragonfly, it doesn’t piggyback off an existing windows speech recognition instance the same way that it would with Dragon NaturallySpeaking. Instead, it creates its own  Windows speech api instance that doesn’t seem to implement any of the convenience functions that the full  Windows speech recognition program would implement.  This means that commands used to correct and re-train the engine, all window management, as well as the commands to start and stop speech recognition are all missing. As a result, once you start caster, there is no stopping or pausing the speech recognition without killing the program altogether, which might not be desirable.

**Comment by LexiconCode** [comment]
Yes we switched in dragonfly to [Sapi5InProcEngine](https://github.com/dictation-toolbox/dragonfly/pull/58) from `Sapi5InProcEngine` This [issue](https://github.com/dictation-toolbox/Caster/issues/305) discovered in caster then pursued further in [dragonfly](https://github.com/dictation-toolbox/dragonfly/issues/41).

During my testing I didn't think to check the builtin WSR commands. Thank you for bringing that to our attention. However I'm not sure what we can do to fix it even in dragonfly as it was particularly difficult debug. There is a lot of info in the above links as you're welcome to give it a shot! Danesprite should be able to give you a few pointers as well on the dragonfly gitter channel.

Open up an issue in the dragonfly repository noting about the lack of commands with WSR.

**Comment by daanzu** [comment]
You can still start the shared SAPI engine (which includes all those other commands) with `get_engine('sapi5shared')`.

Also, I have a grammar that can replace the stop listening functionality. I'll try to get it released soon.

**Comment by Danesprite** [comment]
The stop/start listening behaviour could probably be replicated for the SAPI5 in-process engine using an exclusive grammar. @daanzu I'm guessing this is what you had in mind?

**Comment by daanzu** [comment]
@rakeshnbabu I have a PR with an example [here](https://github.com/dictation-toolbox/dragonfly/pull/91/commits/e5310d0dd294ea1b19eddaf8aa63dbe49287629c). However, it requires the other changes to work.

**Comment by daanzu** [comment]
@rakeshnbabu BTW, this was merged and is in dragonfly 0.15.0.
