### ISSUE TITLE
Move all long extras lists to tomls

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#566]
I really like the "website to bring me as function lists caster issue" functionality of bringme.

A major feature of that function is it adds the new object and refreshes the items making them available without rebooting dragon. This should be available for function/item lists like those in `r.py` and `latex.py`.

This issue should perhaps wait until we move the grammar files to the user folder, which @mrob95 has in progress I believe.

**Comment by kendonB** [comment]
Something like this 

https://github.com/mrob95/MR-caster/blob/master/caster/config/r.toml
https://github.com/mrob95/MR-caster/blob/master/caster/ccr/r.py

**Comment by LexiconCode** [comment]
we don't depart from the dragonfly format which we shouldn't using moving functions to a list in the toml format. Almond all this could be a good move. The only downside is having a lot of files for a grammar but at this point it's one grammar.

**Comment by LexiconCode** [comment]
I would wait on this until we can reload the grammars without restarting the engine. That should come before mid July.
