### ISSUE TITLE
Add code to check for required dragonfly version

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#568]
As per the gitter chat.

**Comment by kendonB** [comment]
There should probably be dependency checking near the top of _caster.py so that no Caster modules load unless the required version of a package is installed. E.g. accepting lists for AppContext titles and executables is new in dragonfly2 version 0.14.0.
This would make it easier for people to see what's going on.
Something like this:
import pkg_resources
pkg_resources.require("dragonfly2 >= 0.14.0")

**Comment by LexiconCode** [comment]
All right @kendonB let's see if it works on bounty source. I think it will trigger when you close the issue.

**Comment by kendonB** [comment]
I have tested your fix and it forced me to install the new version of dragonfly. Great! closing
