### ISSUE TITLE
Caster Crashes On Load When Engine Is Not Defined In Settings.toml

### ISSUE THREAD

**Issue by rakeshnbabu** [dictation-toolbox/Caster#569]
When starting caster, if settings.toml does not have a value for ENGINE_PATH, caster fails to load with the following error message:

```
(dragonfly) C:\Users\rbabu01\dictation-toolbox\Caster>python _caster.py
Searching Windows Registry For DNS...
Cannot find dragon engine path
Setting engine path to
Error saving settings file
Traceback (most recent call last):
  File "_caster.py", line 13, in <module>
    from castervoice.lib.ccr.standard import SymbolSpecs
  File "C:\Users\rbabu01\dictation-toolbox\Caster\castervoice\lib\ccr\__init__.py", line 3, in <module>
    from castervoice.lib import utilities
  File "C:\Users\rbabu01\dictation-toolbox\Caster\castervoice\lib\utilities.py", line 28, in <module>
    from castervoice.lib import settings
  File "C:\Users\rbabu01\dictation-toolbox\Caster\castervoice\lib\settings.py", line 196, in <module>
    "ENGINE_PATH": _validate_engine_path(),
  File "C:\Users\rbabu01\dictation-toolbox\Caster\castervoice\lib\settings.py", line 108, in _validate_engine_path
    print("Error saving settings file ") + str(e) + _SETTINGS_PATH
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
This error is caused by an misplaced parenthesis in the error handling code, but there is another error upstream of this with regards to handling missing paths.

**Comment by LexiconCode** [comment]
Good find, I can reproduce this error with DNS. 

Steps to reproduce
1. The delete the `path` in `ENGINE_PATH` 
2. Then restart Dragon
3. The above error is produced

@rakeshnbabu I assume this is the same steps to reproduce for WRS?

Note: The error is not reproduced if settings.toml is deleted and regenerated during next initialization of Caster.

**Comment by LexiconCode** [comment]
@rakeshnbabu Could you post the link to that upstream issue?

**Comment by LexiconCode** [comment]
Fixed misplaced parenthesis in the error handling code in https://github.com/dictation-toolbox/Caster/commit/75a08cecf0092c16be8adeec05d17b1c3bc878d5#diff-611e9f7b810e1bc7cfd7f2313356831eR102
