### ISSUE TITLE
file to bring me as name not working

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#575]
Saying "file to bring me as file name" currently adds the folder name in the file dialog to the file section of the `bringme.toml` file. I'm actually not sure if there is a feasible way to allow bring me add to work for files. 

Unless someone has an idea of how to achieve this, we should disable `file` as an option for bring me add. Perhaps a nice middle ground would be to have the `bringme.toml` file open at the location of the new line.

Other ideas are welcome.

**Comment by comodoro** [comment]
What it did was take highlighted text, assume it is a file path and add it to things to launch. I suppose this functionality could be restored, plus check if file exists, plus maybe actually detecting current file if in Windows Explorer

**Comment by kendonB** [comment]
I have a "Copy as path" in the context menu on mine with keyboard shortcut "a". So fixing this could be as simple as doing `Key("s-f10, a")` which also looks like it works for folders.
