### ISSUE TITLE
Consider the positives and negatives of using CCR/QuickFluid rules

### ISSUE THREAD

**Issue by lexxish** [dictation-toolbox/Caster#576]
Consider the positives and negatives of using MergeRules vs DragonFluid rules for CCR. Further, consider how we want to implement rules that can merge with each other. Lastly, consider where this code should live.

MergeRules are a seemingly more complex implementation of CCR with unclear separation of concerns between the classes involved. It has app rules, global rules and self modifying rules (which are seldom used) rather than a more general concept of registry grammar. At an API level merge rules are clear to use. When I tested merge rule added as an app rule against dragonfluid rules with commands such as "down 2, left, up 3, right" I found the CCR to be functional on the dragonfluid rule but not the merge rule implementation.

Dragonfluid rules have a much simpler implementation with a logical separation of objects (RegistryGrammars/Rules). Dragonfluid rules have a strange API for creating new rules which requires you to pass the grammar `QuickFluidRules(grammar)`, but this is patched and tested in my fork https://github.com/lexxish/dragonfluid `QuickFluidRules()`. DragonFluid rules will not parse extras to determine CCR eligibility so any command that starts with extras will not be CCR enabled. It's unclear whether MergeRules can handle commands that start with extras.

Note that neither rule allows actual merging of CCR rules. A naive implementation of a merge is to create a hierarchy and merge the maps, having children override parents (I have implemented this with no issue), but we will likely want to parse the specs to handle conflicts. 

FYI @LexiconCode @Danesprite

**Comment by synkarius** [comment]
A couple thoughts here. 

1. If you want Dragonfluid commands, or any other Dragonfly-based commands, to work with Caster, just wrap them in an `R` element. That is Caster's standard mechanism for cross-library compatibility. If Dragonfluid's commands register themselves with the speech engine independently, that won't work of course, but since that breaks with the Dragonfly model, I do not think it is worth supporting.
2. I do not think I fully understand what you are proposing. What is a registry grammar, and how does it functionally differ from what Caster and Dragonfly do?
3. The commands in a MergeRule may start with extras, just like normal Dragonfly commands.

**Comment by lexxish** [comment]
Thanks @synkarius. I'll respond to each number. Keep in mind I'm new to these libraries and these are just my impressions over a short time. 

1. What are the benefits to wrapping in R over what dragonfluid implements (other than extras can start commands)?
2. RegistryGrammar is a group of rules similar to a Grammar but can also activate/deactivate rules. I was proposing to use a library for CCR and to add CCR rule merging to it and perhaps other features. I had a few motivations here:
- The code related to CCR and rule merging should not be application specific so I thought it would be good to build a library and either merge it into dragonfly or keep it as a library on top of dragonfly (I had thought we'd build that library off of Dragonfluid, but perhaps Caster's implementation would be superior).
- CCR rule merging is not implemented in either library (to the best of my knowledge).

3. Awesome!

**Comment by synkarius** [comment]
Noted. I'll respond the same way.

1. Wrapping any Dragonfly command with `R` allows it to be chained together with other commands in Caster's CCR.
2. Caster already has a mechanism to activate/deactivate rules by name and a mechanism to merge rules. However, some rules are incompatible. (Specifically, two rules which contain one or more commands which have overlapping specs are incompatible.) In the event that you attempt to activate a rule which is incompatible with a currently active rule, the new rule will deactivate and replace the old rule. Only rules which do not have overlapping specs are merged.

Let me give an example. Let's say you have three CCR rules (MergeRules), A, B, and C. A and B are incompatible with each other but both are compatible with C independently.

You start with none activated. Then you activate A. At this point, you can chain any of the commands from A together. (They have merged.) Then you activate C. At this point, you can chain together any of the commands from A and C. Then you activate B. B knocks out A, so you have B and C. So you can chain together any commands from B and C.

**Comment by synkarius** [comment]
Incidentally, I'm not married to the compatibility system, but it does keep merging very simple for the user. If you have ideas about other merge modes or something like that, that would potentially be an interesting and valuable project.

**Comment by lexxish** [comment]
Would you all be ok with me moving CCR to dragonfly or creating a new module, say caster-merge-rules, along with adding merging/reloading or other capabilities? @LexiconCode @synkarius @Danesprite 

@synkarius 
1. Is there a way to remove the requirement to use R? Possibly subclassing Text, Key, etc.? What happens if you do R(R(Text("hello")), will that break or cause performance issues?
2. Thanks for explaining more on merging. I believe it could be worthwhile to allow the option of warning the user when an incompatible rule is loaded. What are your thoughts on an optional compatibility system that overrides conflicts, and keeps the rest of the rule loaded? I may have other ideas, will need to give it more thought. The biggest downside I see is it's inheritance without the compile time hints that you're overriding, but the upside is making it easier to use part of one rule in another. Maybe I'm thinking about this wrong though. Perhaps a system of adding rules together where it would fail and error out if there are conflicts would be better. It forces you to split the rules differently but helps you keep track of what is overriding what.

**Comment by synkarius** [comment]
Dragonfly is already capable of CCR without Caster. Caster's CCR is built on Dragonfly's capabilities. But why do you want to move or restructure Caster's CCR/merging stuff? What is the benefit or goal?

1. You could achieve the same thing as wrapping with R by subclassing, sure, but I would again question the purpose. I don't yet see what you're going for. No, wrapping in multiple R's would not create a performance penalty.
2. This part of the conversation is interesting. I have considered this some before, but not at length. Maybe you could go into how it might work to do partial merges like that? What are the problems, what are the potential solutions, can it be made simple for the newcomer, or is it an advanced feature, etc.

**Comment by lexxish** [comment]
I'm unclear, does caster enhance CCR in some way in addition to adding merging? 

The benefits are more clarity, easier to add new features and reusability.

I'm on mobile at the moment but I think different merging modes could be used by average users. I'm not very familiar with the parsing of dragonfly grammars so that would be a challenge. I'd like to find a library that could assist with the parsing ideally. The merging would need to either ignore an entire dictionary element if it conflicts or be capable of parsing partial elements. The main thing to determine when parsing is whether keys that are different actually can resolve to the same grammar, so expanding ORs and evaluating each option, ignoring extra parentheses, etc. One challenge is you could still have phonetic conflicts unless you searched for those too.

**Comment by synkarius** [comment]
Caster adds to Dragonfly's CCR in a few ways. (1) It lets you adjust max repetitions via a setting in the toml config file, which affects max grammar complexity. (2) Merging. Caster comes with a lot of other stuff, but those are the enhancements specific to CCR.

Re: clarity, I think better clarity is achieved through better docs. Caster's docs are semi-respectable, but could certainly use improvement. Can you point to any examples of code which is written in a particularly obfuscating way? 

As for reusability and new features being hindered by structural issues, I'm still not sure I understand what you mean. Can you maybe make a small/simple PR to show something you'd want to change and how it would facilitate those things?

I like where you are going with "merge modes". That is something which I agree that Caster lacks and would be useful. Some parts of what you talked about (phonetic conflicts, discarding extra parens/etc.) seem daunting to me, but if you're willing to take those on, I'd be more than happy to support you in your endeavors.

**Comment by LexiconCode** [comment]
@lexxish Since CCRMerger is going to be rewritten further discussion can be made in the following thread https://github.com/dictation-toolbox/Caster/issues/385
