### ISSUE TITLE
Accepting donations to fund bounty

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#591]
We could open up a donation section. Then the Caster project can donate to sponsor a bounty and/or the bounties can be sponsored by individuals through https://www.bountysource.com/. 

Thoughts on A few guiding principles:
- Transparency through an automated process donations in/bounties out
- In order for bounties to be posted they must have very clear guidelines and resources for those that wish to collect. 
- Each bounty candidate must be discussed with the community with a minimum of seven days for feedback before before the Caster project posts the bounty.

**Comment by kendonB** [comment]
Reposting: I feel strongly that the purse strings should be ultimately controlled by one individual though to prevent disputes. It should be up to that individual to ultimately judge whether a contribution is sufficiently tidy to warrant handing over the money, of course with feedback from the community. That individual should also be responsible for pricing bounties, again potentially with consultation. @LexiconCode is the obvious default person :)

**Comment by LexiconCode** [comment]
What you think of some of the principles @kendonB?

**Comment by kendonB** [comment]
Totally agree

**Comment by LexiconCode** [comment]
Alright so the two things we need to address for this to become reality.

- Research if there's automated process donations in/bounties out.
- Create guidelines for developing an issue for bounty.

**Comment by LexiconCode** [comment]
All right have set up a dedicated email CasterVoice at protonmail c o m.

**Comment by kendonB** [comment]
It looks like it's quite decentralized: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

You submit bounties and interact with the site as individuals. They don't take a cut at the bounty-setting stage but they take 10% upon withdrawal, which seems a reasonable price to pay for the transparent system. Ultimately it relies on PayPal for processing in both directions.

I set up this team: https://www.bountysource.com/teams/caster-dictation/ and will add at least @LexiconCode as an admin.

It doesn't look like it's necessary to have a caster email address.

**Comment by LexiconCode** [comment]
Looks great. Although I don't think I've been added to the project. It's hard to tell but when I look at the members list that states your name only.

**Comment by kendonB** [comment]
You're there now as a full admin. @LexiconCode are you happy to take the job of making final decisions on 1) what bounties get set by the team, and 2) what solutions are good enough to get the award?

**Comment by kendonB** [comment]
Remember that anyone can set a bounty as an individual. It's up to that individual to decide whether a solution solves the bounty, I believe.

**Comment by LexiconCode** [comment]
> 
> 
> You're there now as a full admin. @LexiconCode are you happy to take the job of making final decisions on 1) what bounties get set by the team, and 2) what solutions are good enough to get the award?

Yes with feedback with the maintainers and our current community. Although I would ask that maintainers participate in reviewing solutions for rewards. It's in our best interest to make the most of the bounties rewarded.

**Comment by LexiconCode** [comment]
I wonder if there is a tag we can get to put on the get homepage that were on bounty source.

**Comment by kendonB** [comment]
stickers done

**Comment by LexiconCode** [comment]
All right I'll consider this closed. If any other issues arise we can reopen.
