### ISSUE TITLE
Evaluate each grammar to leverage the features of Caster. 

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#649]
Caster has many apps and ccr grammars written over a large time spent with a variety of authors. Depending on their knowledge and time to contribute they may have not fully leverage features of Casters within the grammar. 

It's time to take in-depth look at each grammar one feature at a time. It could be framed as a question. Could `x` feature be used to enhance `x` spec? The goal being not to add new standalone specs but to enhance the intended original outcome of a spec. To clarify you might also include extras, choices other elements to existing specs within the limits of the stated goal above.

For each feature a new issue should contain the following.
- Check boxed items for the grammars.  
- Title should include `Feature Eval: <feature>` 
- The issue should describe the feature purpose to the best of the ability of contributor. If documentation is available in the code or RTD utilize it. 

As we leverage new features we also will discover limitations of those features. Take some time to document them as they might become future enhancements.

- Features (WIP)
    -  Store and Retrieve Text #650
	-  ContextSeeker

**Comment by kendonB** [comment]
Is #491 an example of one of these features?

**Comment by LexiconCode** [comment]
> Is #491 an example of one of these features?
Something I'm trying to decide on. Initially I would've thought that would fall in the category of adding on specs rather than enhancing existing specs. I'm wondering if my initial thought is too narrow of a scope.

**Comment by kendonB** [comment]
I see. Well starting with what's already there is definitely a good start

**Comment by LexiconCode** [comment]
> I see. Well starting with what's already there is definitely a good start

Thinking out it's more I don't think the scope is too small. Each feature requires looking at every grammar with that feature in mind. That is already quite a lengthy process.

I think #491 would be an example of standardizing features in the same domain might be another future category with a similar process laid out in this issue.

**Comment by LexiconCode** [comment]
One other thing to discuss is whether or not to include multiple features per issue. Technically one could `Store and Retrieve Text` and `ContextSeeker` features at the same time. The major downside to doing to is it requires contributors to learn possibly to new aspects of Caster at the same time. In addition what's to change it from being three features and so forth causing information overload for contributors. 

My initial thought was to keep this bite sized as possible. In addition by tracking pull request by each grammar See (https://github.com/dictation-toolbox/Caster/issues/650). Other contributors can see how the X feature is implemented as a reference for contributing their own work with the same feature.

**Comment by kendonB** [comment]
I don't think I have strong feelings about issue sizes. I think that people are smart and can figure out how to make solutions that partially solve large issues as well as solutions that solve a few small issues. Probably easier to start big then split later if needed
