### ISSUE TITLE
Attempt transformers safely

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#695]
KB: I had a mistake in one of my transformers and upon reload the whole system doesn't work.

Would be good if we could work out a way to get the transformations to be attempted safely.

synkarius:

So here's a problem with the transformers system: there are very limited post-transformer validations. (See `_post_transform_validate`.) Adding them in would be a good way to solve this problem, IMO. I strongly recommend taking those existing post-transformer validations (which were done quickly) and turning them into proper validators like all the other validators that new Caster uses, and then adding to them. Basically I have no way to check what kind of weird stuff people do in transformers ahead of time, no way of knowing how people might creatively break the system, so you've just got to do validations as problems come up if you want to prevent this kind of thing.

But you guys are correct to point out that this is out of the scope of this rewrite, as one bad filter function could also have brought the house down in the prior system. It just so happens that no one ever actually used filter functions.

**Comment by LexiconCode** [comment]
Closing due to transformers being removed from the rewrite.
