### ISSUE TITLE
Bring me folder not always bringing to foreground

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#697]
**Describe the bug**
"Bring me folder" commands do not always bring the Explorer window to the foreground

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Say "bring me caster user"

**Expected behavior**
Sometimes the Explorer window comes to the front and sometimes it doesn't. We expect that it should always come to the front. Currently we are using `Popen`. @Danesprite, does `BringApp` do a better job at bringing things to the foreground?

**Comment by Danesprite** [comment]
Yes, BringApp does a better job. It will bring an existing window to the foreground if it matches. It looks like the current implementation doesn't do that, so I'm not sure if that's what you want. Try using BringApp and see if it fixes the problem.

If this problem occurs when an elevated/admin window is active, then it's not something we can fix.

**Comment by LexiconCode** [comment]
@kendonB this seems to be resolved for me, can you confirm?

**Comment by LexiconCode** [comment]
As this seems to be resolved I'm closing the issue.
