### ISSUE TITLE
Speed up Legion using sampling and/or subsets of the screen

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#701]
**Is your feature request related to a problem? Please describe.**
Legion exhibits noticeable latency due to the computational requirements of the algorithm. This is especially noticeable on a 4K display (@LexiconCode said this once).

**Describe the solution you'd like**
It would be good to down sample the image to only what is required to detect the text on the page before processing.

Additionally, we could limit the bounds of the image using a number from 1 to 9 denoting a region of the screen.

**Comment by LexiconCode** [comment]
That's an interesting thought and shouldn't be too difficult to do at least in the portion of downscaling a screenshot. However scaling it to the current screen afterwards is a bit of an unknown to me.

**Comment by ethangoldstein** [comment]
I have some experience dealing with image processing. Computations on images are very processor taxing, especially once the image size becomes 4k. Capturing a screenshot and then down sampling it would require even more processing as it would have to be low pass filtered and then decimated. The GPU is designed for these types of computations, not the CPU. It may be worth sending the computations to the graphics card. Another potential solution is the write the computationally expensive part in C. I have had success with that in the past using Cython.

**Comment by kendonB** [comment]
> Another potential solution is the write the computationally expensive part in C.

I would hope there's a package that has already done this

**Comment by LexiconCode** [comment]
> > Another potential solution is the write the computationally expensive part in C.
> 
> I would hope there's a package that has already done this

For image manipulation Caster already utilizes [Pillow](https://python-pillow.org/) library. Pillow which leverages the power of the C directly (rather Cython) than wrapped up in Python. It does not leverage GPU instances like (CUDA) but runs on CPU.

Premature optimizations undesirable. However profiling or even just simply using timeit to see which part of the process is taking longer. 

`castervoice\asynch\mouse\legion.py`  is where "tirg-32.dll" ts loaded for Legion and gdi.

`castervoice\lib\gdi.py` mostly deals with grabbing the image on the screen for processing.

**Comment by kendonB** [comment]
This one was partially addressed in #788. https://github.com/kendonB/Caster/tree/downscale_legion2 implements subsets of the screen but finds no major speed up. It seems like the big bottleneck is actually spinning up the process. Closing for now.
