### ISSUE TITLE
Visual C++ Runtime Error R6034 on Dragon launch

### ISSUE THREAD

**Issue by zilch42** [dictation-toolbox/Caster#705]
Hi, 

I'm getting a Visual C++ Runtime Error R6034 whenever I launch DNS after installing Caster. I've done this on 2 computers and it's happening on both. On the second, I checked DNS after each install of Python, PyWin, NatLink, and then Caster. It was definitely Caster. 

DNS seems to open and run fine after the error. I haven't encountered any actual issues in use so it may just be an annoying error. But I thought I'd flag it. If I run into any real problems I'll update this issue. 

Windows 10
Dragon Professional Individual 15.3
Python 2.7.17
Natlink 4.2
Caster 1.1.3

**Comment by LexiconCode** [comment]
Thanks for a thorough report! This is probably related to the the Legion command/workspace which load .dll.

Try installing [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-in/download/details.aspx?id=5555)

**Comment by kendonB** [comment]
is your Windows 10 up-to-date? I thought that the latest version was shipping these by default

**Comment by LexiconCode** [comment]
There's potential for natlink to be at the root cause as well. See [source](https://www.knowbrainer.com/forums/forum/messageview.cfm?catid=25&threadid=23887). We will go down that road at the above suggestion does not work. Likewise I thought Windows 10 comes with `Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019.`

**Comment by zilch42** [comment]
Thanks guys. Windows 10 is up-to-date. I installed the redistributable visual studio 2015, 2017 and 2019. The 2010 installer said I already had a newer version installed. Still getting the runtime error.
@LexiconCode I checked out the suggestion in the source link. The readme file said that it shouldn't be tried on Windows 10. Any thoughts about that?

**Comment by zilch42** [comment]
Also, I haven't learned how legion works yet but when I say legion the numbered overlay does come up. Not sure if that's any help?

**Comment by LexiconCode** [comment]
Does the error message happen before or after the status window appears?

**Comment by zilch42** [comment]
Before. Order:
Dragon - Loading User Profile
Dragon - Initializing
Runtime Error
Click Ok on Error
Caster status window + Dragon - Initializing
Everything finished and happy

**Comment by kendonB** [comment]
If you empty out the caster folder still leaving the top directory there, do you still see the error?

**Comment by zilch42** [comment]
Sorry which one? C:\Users\ME\Documents\Caster\
(with Caster-master inside)
or 
C:/Users/ME/.caster
(with data, rules, hooks, etc inside) ?

**Comment by LexiconCode** [comment]
To experiment
You can delete or move the contents of `C:\Users\ME\Documents\Caster`
or
You can use the Natlink GUI `start_configurenatlink.py` and change the directory from castor to anywhere else.

The goal is to take it caster out of the speech recognition stack.

**Comment by zilch42** [comment]
Got it. Moved Caster-master to my desktop (that's all that was in there). Still get the error.

**Comment by LexiconCode** [comment]
> @LexiconCode I checked out the suggestion in the source link. The readme file said that it shouldn't be tried on Windows 10. Any thoughts about that?

Because I'm unsure I think we might need to seek out more support from the community abroad. This is either an issue with Natlink or Dragon.
1. http://www.knowbrainer.com/forums/forum/categories.cfm?catid=25
2. https://gitter.im/dictation-toolbox/dragonfly?source=orgpage

I can follow along with either of these two places that have some very knowledgeable hopeful folks.

**Comment by LexiconCode** [comment]
@zilch42 The issue is related to Natlink in an [in-depth discussion](https://groups.yahoo.com/neo/groups/VoiceCoder/conversations/topics/7925)

I will update the Troubleshooting FAQ.

Thanks again for opening up the issue!

**Comment by zilch42** [comment]
No worries. Thanks for looking into it!
