### ISSUE TITLE
Document activating simple transformers

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#715]
**Describe the bug**
Simplified transformers have no effect when active.

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Create a `words.txt` in `.caster/transformers`
```
<<<SPEC>>>
shock -> earthquake
<<<NOT_SPECS>>>
sauce -> up
dunce -> down
lease -> left
```
3. Restart Dragon
4. See on restart `Text replacing transformer from file 'words.txt' activated ...`
6. definitions `words.txt` have no effect

**Comment by LexiconCode** [comment]
As a concept Transformers have failed see the following [for reference](https://github.com/synkarius/Caster/issues/43). Simplified transformers rely on the underpinnings for Transformers and Therefore this bug may not be fixed.

**Comment by kendonB** [comment]
Have you switched the item to true in transformers.toml?

**Comment by LexiconCode** [comment]
@kendonB You are correct! Have been until recently since the rewrite deleted my `.caster` folder. I wondered if I was missing something simple and that was it.

**Comment by kendonB** [comment]
Should we leave this open as a reminder to document it
