### ISSUE TITLE
The Caster settings GUI does not display

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#723]
**Describe the bug**
The Caster settings GUI does fails to launch and does not display.

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Say `launch settings window`
2. See error

```
HMCLaunch: launch settings window
2020-01-08 09:28:08,183 : ERROR : execute
Execution failed: %s
2020-01-08 09:28:08,216 : ERROR : execute
Execution failed: %s
unnamed command (A)
```

**Expected behavior**
The GUI should launch and display settings from `settings.toml`

**Comment by Versatilus** [comment]
`settings.initialize()` needs to be called somewhere around here: https://github.com/dictation-toolbox/Caster/blob/master/castervoice/asynch/settingswindow.py#L17

That fixes the launching problem, but for some reason the `formats` tab broke. I'm going to look into it after dinner.

**Comment by LexiconCode** [comment]
> 
> 
> `settings.initialize()` needs to be called somewhere around here: [/castervoice/asynch/settingswindow.py@`master`#L17](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/asynch/settingswindow.py#L17) [](/dictation-toolbox/Caster/blob/HEAD@{2020-01-09T00:20:50Z}/castervoice/asynch/settingswindow.py#L17)
> 
> That fixes the launching problem, but for some reason the `formats` tab broke. I'm going to look into it after dinner.

 I think it's a bit more than the `formats` or `gitbash` tab  in fact it is anything that's an integer.

**Comment by Versatilus** [comment]
I have it fixed, but I don't like the way it looks. It might take me the
rest of the night to get it where I'm satisfied.
