### ISSUE TITLE
Problems with Sudoku grid

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#733]
**Describe the bug**
@ithmeer the sudoku grid is a great innovation. Many thanks for this. I have noticed that it's still a little buggy when using a second monitor.

 - When I try to move the cursor by saying one of the numbers, the cursor ends up moving on the first screen not the second.
 - The size of the rectangles on the second monitor is much larger than the first

**To Reproduce**
1. Use two monitors
2. Say 'sudoku 1', 'terminate', then 'sudoku 2'

**Expected behavior**
The size of the squares should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/5327505/72690258-78b16b00-3b7f-11ea-9e84-2132150791af.png)
![image](https://user-images.githubusercontent.com/5327505/72690266-94b50c80-3b7f-11ea-9927-6747a8b0f7d1.png)

**To Reproduce (second bug)**
1. Use two monitors
2. Say 'sudoku 2', then one of the numbers

**Expected behavior**
The cursor should move to that location on the second screen but it moves to that location on the first screen.

**Comment by qubitz** [comment]
Thanks for the write up @kendonB. I have also noticed this and I have found that Rainbow and Legion do not share this bug.

**Comment by LexiconCode** [comment]
I can't really troubleshoot this moment as I do not have a second monitor set up.
