### ISSUE TITLE
Old Docs 

### ISSUE THREAD

**Issue by RyanQuey** [dictation-toolbox/Caster#741]
**Describe the bug**
It appears that [this link](https://caster.readthedocs.io/en/latest/readthedocs/Examples/rules/Caster_Rules/) is no longer up to date, is that correct? 

For example, `from caster.lib import control` is raising an error, saying that "caster"does not exist as a folder. 

I'm trying to migrate to the latest caster version, but having a hard time when following examples listed here (though they match my old caster files which worked). This could very well be my fault though, since I'm still getting used to the caster source code. 

Thanks!

**Comment by LexiconCode** [comment]
Greetings Ryan!

Yes the documentation is out of date. It's in the process of being rewritten and reorganized. I'll definitely need feedback from once it's released.

Meantime there are a few resources I can give you to jumpstart migrating your Grammars to Caster 1.x.x

[Caster 1.0.0 Changes Summary](https://github.com/dictation-toolbox/Caster/issues/385#issuecomment-529165483)

[RuleTemplates.zip](https://github.com/dictation-toolbox/Caster/files/4153494/RuleTemplates.zip)

**Comment by RyanQuey** [comment]
This is fantastic, that was going to be my follow up question! Thank you so much!
