### ISSUE TITLE
Simplified Transformers ignore specs with extras

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#770]
**Describe the bug**
Any spec with `<>` to define an extra is ignored by Simplified Transformers.

**To Reproduce**
```
"(open file | go to [tab]) <text>":
            R(Key("c-p") + Text("%(text)s"), rdescript="VS Code: Go to File without using dialogbox"),
```

1. Go to 'words.txt'
2. Add `(open file | go to [tab]) <text> -> open file <text>` as a replacement
3. Restart Caster

Note: It is not possible to remove `<text>` a define an extra. The replacement spec must have the <text> extra. The whole command will become invalid as action if the extra is transformed to undefined reference in the grammar.

**Comment by LexiconCode** [comment]
The unit [test_textReplacerTransformer.py](https://github.com/dictation-toolbox/Caster/blob/master/tests/lib/merge/ccrmerging2/transformers/text_replacer/test_textReplacerTransformer.py) tests test for `extra` like `<text>`.

I've also verified by temporary adding [test_TRParser.py](https://github.com/dictation-toolbox/Caster/blob/master/tests/lib/merge/ccrmerging2/transformers/text_replacer/test_TRParser.py) to make sure that the parser was not ignoring extras as well.

Given that both of these unit texts work with extras I am unsure how to further troubleshoot the issue.

**Comment by mpourmpoulis** [comment]
Only taking a very quick look at it but The text replacer appears to be preprocessing rule specs by changing all the references to extras into `<?>` before matching them against user supplied overrides ( Which still retain the original `<text>`And therefore they don't match)

https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/merge/ccrmerging2/transformers/text_replacer/text_replacer.py

(_preserve)

**Comment by synkarius** [comment]
This is ready for testing. It's been a while since I committed a bug fix. What's the procedure?

**Comment by LexiconCode** [comment]
The python 2.7 because of  "The remote server returned an error: (503) 
Server Unavailable.". Which I believe means are being rate limited by onedrive. Which I tried as an alternative to the way back machine archive as it was really slow. The supposed alternative service is needed.

As for the procedure normally I open up PR if it addresses a specific issue that's documented.

**Comment by synkarius** [comment]
I must have been pretty tired last night. Obviously it's a PR. Thanks, haha.

**Comment by synkarius** [comment]
Also, thank you @mpourmpoulis. Your description was spot on, which made fixing this much faster.

**Comment by LexiconCode** [comment]
I will work on some testing this coming Sunday.

**Comment by mpourmpoulis** [comment]
No worries @synkarius Glad This got resolved
