### ISSUE TITLE
The Sikuli server fails to import `six` module.

### ISSUE THREAD

**Issue by masisley** [dictation-toolbox/Caster#778]
**Describe the bug**
The Sikuli server fails to start

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Install the latest version of Sikuli
2. Enable it in settings.toml
3. On caster start we fail to connect the server.

If you attempt to start the server manually yourself, you will receive error: 
java -jar C:\Users\{USERNAME}\Documents\Sikuli\sikulixide-2.0.4.jar -r C:\Users\{USERNAME}\Documents\Caster\castervoice\asynch\sikuli\server\xmlrpc_server.sikuli --args

[error] script [ xmlrpc_server ] stopped with error in line 1
[error] ImportError ( No module named six )
[error] --- Traceback --- error source first
line: module ( function ) statement
1: main (  <module> )     import six
[error] --- Traceback --- end --------------

I have validated that I have the latest version of six installed. "import six" from a python command line works. Six is used several places in the caster project without issue.

**Expected behavior**
The sikuli server should start up and we should be able to use it.

**Screenshots**

**System:**
 - OS: [e.g. iOS] Windows 10
 - Program: [e.g. chrome, eclipse, atom] Sikuli 
 - Version: [e.g. 22] v2.0.4

**Comment by LexiconCode** [comment]
Thanks for the bug report!

I tested and was able to reproduce this with SikuliX `1.1.4`, `2.0.1`, and `2.0.4`.

It turns out SikuliX for whatever reason doesn't like utilizing `six` module. Simply replacing it with `sys.version_info` in `xmlrpc_server.sikuli`

```
import os
import sys

if sys.version_info[0] < 3:
    from SimpleXMLRPCServer import SimpleXMLRPCServer   # pylint: disable=import-error
else:
    from xmlrpc.server import SimpleXMLRPCServer  # pylint: disable=no-name-in-module
```

Go ahead and test and let me know!

**Comment by LexiconCode** [comment]
Something else that cropped up during testing.
```
ERROR:action.exec:Execution failed: Playback failed: No matching rule found for words ['enable', 'sikuli', 'custom'].
```
Without manually activating the grammar by saying `enable sikuli custom` are your sikuli available for recognition?
