### ISSUE TITLE
WSR fails to initialize if microphone already in use.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#821]
**Describe the bug**
Launching WSR Caster Python 2.7.18 64-bit
```
Running WRS from Dragonfly CLI.
INFO:engine:Selecting audio source: u'Microphone (Realtek High Definition Audio)'
INFO:module:CommandModule('_caster.py'): Loading module: 'C:\Users\User\Documents\Caster\_caster.py'
Caster User Directory: C:\Users\User\AppData\Local\caster
Could not import 'again'. Module has errors: Traceback (most recent call last):
  File "castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 121, in _import_module
    return load_fn(module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\User\Documents\Caster\castervoice\rules\ccr\recording_rules\again.py", line 10, in <module>
    _history = recognition_history.get_and_register_history(10)
  File "castervoice\lib\util\recognition_history.py", line 6, in get_and_register_history
    history.register()
  File "C:\Python27\lib\site-packages\dragonfly\grammar\recobs.py", line 61, in register
    engine.register_recognition_observer(self)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\engine.py", line 197, in register_recognition_observer
    self._recognition_observer_manager.register(observer)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\recobs.py", line 62, in register
    self._activate()
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_sapi5\recobs.py", line 42, in _activate
    self._grammar.load()
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 353, in load
    self._engine.load_grammar(self)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\engine.py", line 138, in load_grammar
    wrapper = self._load_grammar(grammar)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_sapi5\engine.py", line 150, in _load_grammar
    handle.CmdSetRuleState(rule.name, constants.SGDSActive)
  File "C:\Users\KYLEM~1.DOU\AppData\Local\Temp\gen_py\2.7\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\ISpeechRecoGrammar.py", line 67, in CmdSetRuleState
    , State)
com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2004287480), None)

The rule GrammarActivatorRule was set to active.
The rule HooksActivationRule was set to active.
Skipping rule Again because it is enabled but not loaded.

*- Starting Caster v 1.6.16 -*
```

**System:**
 - OS: Windows
 - Program: WSR
----

**Comment by LexiconCode** [comment]
Possible related issue https://github.com/dictation-toolbox/Caster/issues/68

I've had success running WSR Python 3.8.2 64-bit/32-bit. 
- [ ] Test my other machine for Python 2.7.18

**Comment by kmdouglass** [comment]
I also get the same error when using pure Dragonfly:

```
python -m dragonfly load --engine sapi5inproc sample.py --no-recobs-messages
```

**Comment by LexiconCode** [comment]
Well at least it narrows down the stack down to dragonfly. 

This would be unlikely but it's good information to have. 

What build version of Windows?
What version of WSR?
What version of win32?

**Comment by kmdouglass** [comment]
> What build version of Windows?

Version 1909, build 18363.836

> What version of WSR?

I'm not sure how to find this, but the "About..." window for the WSR states: `Microsoft speech recognizer 8.0 for Windows`

> What version of win32?

I googled for this but failed to find a way to find the version of win32. (I primarily use Linux and am a bit lost in Windows.)

I also tried but failed to decipher the error codes from the traceback using the win32api package from Python:

```
>>> import win32api
>>> win32api.FormatMessage(-2147352567)
'Exception occurred.\r\n'
>>> win32api.FormatMessage(-2004287480)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (15100, 'FormatMessage', 'The resource loader failed to find MUI file.')
```

**Comment by kmdouglass** [comment]
Okay so I made some progress. My laptop is from MSI. Yesterday before testing Caster I downloaded and installed the latest drivers from MSI which includes a program called that is called Nahimic. This program is a daemon that allows you to tune properties of the microphone through its software interface. I killed the running instances of the daemon and relaunched Caster. The result is that the traceback disappears and Caster recognizes commands such as “arch” and “enable firefox.”

I suspect that Caster was competing with Nahimic for a locked resource, namely the microphone.

This now leads me to the next problem. I can confirm that Caster is recognizing my voice commands and that the Firefox rule is enabled by looking at the Caster log window. However when I have Firefox open, none of the commands actually do anything. Firefox just sits there unresponsive to my commands.

Would you prefer that I ask follow-up questions on the chat, in this ticket, or a new ticket?

**Comment by LexiconCode** [comment]
> Okay so I made some progress. My laptop is from MSI. Yesterday before testing Caster I downloaded and installed the latest drivers from MSI which includes a program called that is called Nahimic. This program is a daemon that allows you to tune properties of the microphone through its software interface. I killed the running instances of the daemon and relaunched Caster. The result is that the traceback disappears and Caster recognizes commands such as “arch” and “enable firefox.”

Nice work! So it does really relate back to #68 with how the microphone is initialized. if that interface is busy that errors produced. 

> Would you prefer that I ask follow-up questions on the chat, in this ticket, or a new ticket?

I think basic troubleshooting is okay in chat is okay and if it turns out to be something significant an issue can be opened.

**Comment by LexiconCode** [comment]
Documented in WSR install troubleshooting FAQ

https://github.com/dictation-toolbox/Caster/commit/f795116ff52b633ee8636c4c98a7e41989d0b8a9
