### ISSUE TITLE
Option to configure user directory

### ISSUE THREAD

**Issue by Timoses** [dictation-toolbox/Caster#842]
**Is your feature request related to a problem? Please describe.**
I would like to use another user directory. Currently, it seems to be only possible by modifying `castervoice/lib/settings.py` (or perhaps via some other hacks).

**Describe the solution you'd like**
* Caster could read a environment variable such as `USER_DIR`
  * Considering below comment on additional context I'd suggest using `CASTER_DIR` instead

**Describe alternatives you've considered**
* Additional argument options could be passed to python (e.g. `python -m dragonfly load _*.py --caster-user-dir ...`)
  * This would probably require a change in dragonfly to allow unknown arguments to pass through (not sure whether that would be a desired behavior on the side of dragonfly).
* another option would be to read a configuration file within the current directory (though the environment variable sounds preferable to me) 

**Additional context**
`{user_home}/caster/settings/settings.toml` does contain `USER_DIR` as a configuration. However, does it make sense defining it there?
I'd even go as far as proposing another name for "user dir". Shouldn't it be named "caster_dir"? Considering at some point Caster would be available in some kind of packaged format it would make sense to pass it this as an argument. `user_dir` sounds a bit wrong (as it naturally describes a user's home directory which is NOT where caster should store its content, but rather in a subdirectory thereof by default - which it currently does without any other configuration option available to change this behavior).

**Comment by kendonB** [comment]
This would also make it easier to develop caster to temporarily use a fresh user directory.
