### ISSUE TITLE
castervoice.lib.util.pathlib.Path removes leading `/` from path

### ISSUE THREAD

**Issue by Timoses** [dictation-toolbox/Caster#844]
**Describe the bug**
This concerns `castervoice.lib.util.pathlib`.

```
print(Path(str(Path("/testpath"))))
```
prints `testpath` instead of `/testpath` on MacOS.

```
print(Path(unicode(Path("/testpath"))))
```
corrently prints `/testpath`

This might be concerning as `str` is used here: https://github.com/dictation-toolbox/Caster/blob/bd1f07cb04a3f288a597a8aed7f784ab99eba7fc/castervoice/lib/settings.py#L483

Whereas `user_data_dir` returns a `unicode` object (see https://github.com/dictation-toolbox/Caster/blob/bd1f07cb04a3f288a597a8aed7f784ab99eba7fc/castervoice/lib/settings.py#L482)

**To Reproduce**
Add above snippets to `castervoice/lib/settings.py` and watch output.

**Expected behavior**
Path should not drop leading `/`.
(Tested this in a Linux Container and it printed `/testpath` both times)

**System:**
 - OS: MacOS , Python2.7
 - Program: -
 - Version: 1.6.16

**Comment by Timoses** [comment]
Note: With Python3 there is no issue.

**Comment by LexiconCode** [comment]
I appreciate the issue! It's good to have another set of eyeballs on the code :)

If memory serves due to encoding issues a modified version of Pathlib2 was integrated into Caster. Required bug fixes were not going to be accepted upstream into Pathlib2. I mentioning that just for some context.

I would've thought unicode would've been handled by `from builtins import str`. Not picking it up on Windows but I will fire up Linux. I definitely could miss something here!

```
from builtins import str 
import sys, six
sys.path.append(r"D:\Backup\Library\Documents\Caster")

if six.PY2:
    print("Python 2")
    from castervoice.lib.util.pathlib import Path
else:
    print("Python 3")
    from pathlib import Path  # pylint: disable=import-error

print("str")
print(Path(str(Path("/testpath"))))
print("unicode")
print(Path(unicode(Path("/testpath"))))
```

output
```
PS C:\Users\Main\Desktop> C:\Python27\python.exe testme.py
Python 2
str
b'\testpath'
unicode
\testpath
```

**Comment by LexiconCode** [comment]
Based on the following factors i'm thinking it's not worth the time to fix this:
- Platforms besides Windows require python 3 with the official install instructions
- I cannot reproduces on Windows\Linux python 2.7.18 64 bit
- As soon as Natlink has a python 3 compatible installer we will drop python 2 on all platforms.
