### ISSUE TITLE
Dictating the word "point" removes spaces before and after the word

### ISSUE THREAD

**Issue by MarkRx** [dictation-toolbox/Caster#862]
**Describe the bug**
When dictating the word "point" using Caster spaces are removed before and after it. The Dragon dictation popup shows the correct words. When using Dragon in dictation it works correctly.

_Update_ - see https://github.com/dictation-toolbox/dragonfly/issues/311

**To Reproduce**
1. Say "cop what is the point of that questo"
2. Output is "What is thepointof that?"

**Expected behavior**
Output is "What is the point of that?"

**System:**
OS: Windows 10
Program: Any
Version: Caster master 3f45fbb, dragonfly 0.27.1
Dictation Engine: Dragon Pro 15

**Comment by MarkRx** [comment]
I found it. It's from this: https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_natlink/dictation_format.py#L339 and https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_natlink/dictation_format.py#L412. It broke with https://github.com/dictation-toolbox/dragonfly/commit/f8e8f8b26c84d2493ca2a52d67b4b78f01b386eb

**Comment by kendonB** [comment]
Appears to be fixed in dictation-toolbox/dragonfly#311 

Reopen if not.
