### ISSUE TITLE
Upgrading Dragon with Natlink install to Python 3.10.x 32-bit

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#911]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24350%20Funded-%2300A156.svg" />](https://issuehunt.io/r/dictation-toolbox/Caster/issues/911)

Blocking issue which needs to be remedied for Python 3.10.x 32-bit Natlink users. For now the master branch is recommended until the block is resolved. https://github.com/dictation-toolbox/Caster/issues/932

Caster has had support for Python 3 for a long time. In fact all other engines utilize Python 3 64-bit. There is still some cleaning up to do. I would like a proper release before supporting Python 3 for Dragon. During that time I'm working with people in the Dictation Toolbox community to test Natlink.  All that is to say you're welcome to give the try and definitely let me know if you run into anything by posting issues [here](https://github.com/dictation-toolbox/natlink/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) in the Natlink Repository. 

These instructions work for any natlink based project like dragonfly or caster.

Preinstall requirements
- DPI 15,14, 13 or derivative of the same version
- Make sure any previous versions of Natlink are unregistered and uninstalled. (Dragon must be close during that process)
- (optionally) If you have tried the the Natlink test package and/or main Natlink repository make sure there's no remnants derivatives of Natlink in the site packages of Python.

1.  Download the caster main branch https://github.com/dictation-toolbox/Caster/archive/refs/heads/master.zip
2.  Unzip into directory as or rename it from Caster-master to `Caster` 
3.  Edit `requirements.txt` remove the following line `wxpython==4.1.0` in the my documents Caster directory
4.  Delete caster settings in caster user directory `C:\Users\%USERNAME%\AppData\Local\caster` (if prior install)
5.  Download the latest [Natlink](https://github.com/dictation-toolbox/natlink/releases)
	- Python 3.10.X 32 bit is required. (if you don't have Python 3.10 installed Natlink Installer will install it off path for you automatically)
	- Do not uncheck the default `py launcher`
6. Run the Natlink Installer and a GUI should pop up at the end

7. Configure the Natlink GUI point to Caster
	- ![image](https://user-images.githubusercontent.com/24551569/208255884-461c6e01-b13d-4f02-a2fe-741e4d503143.png)
8. Install_Caster_DNS-WSR.bat - don't forget to delete `wxpython==4.1.0` in step 3. first-
9. Start Dragon
- ![image](https://user-images.githubusercontent.com/24551569/208255901-1ca9924b-4902-49b3-82d3-29530ef2684f.png)

**Notes**
- Natlink configuration GUI can be launched from Windows start menu
![image](https://user-images.githubusercontent.com/24551569/208255947-b4dd33ef-9c4c-487d-a466-11847a42cda4.png)

Notable changes:
- Distributed as an installer
	- If needed installs 32-bit python for the end user without relying on path for natlink. (makes it easy to use Conda/64-bit Python)
- Standardizes the built environment utilizing C-Make
	- The build system not only builds the C++ code but that installer as well.
	- Builds on VS Code and Visual Studio
- Pruned a lot of the dead code and restructured the project
- Support for DNS/DPI 13, 14 and 15

Follow along on the [natlink](https://github.com/dictation-toolbox/natlink) branch

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $350.00)

- [<img src='https://avatars.githubusercontent.com/u/17401965?v=4' alt='chrisflodin' width=24 height=24> chrisflodin](https://issuehunt.io/u/chrisflodin) ($50.00)
- [<img src='https://avatars.githubusercontent.com/u/5995190?v=4' alt='valkrysa' width=24 height=24> valkrysa](https://issuehunt.io/u/valkrysa) ($300.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/dictation-toolbox/Caster/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by LexiconCode** [comment]
Natlink in the master repo now works with DNS 13/DPI 14 and 15. As soon as the next release this documentation will be integrated into the caster project.

**Comment by exitflynn** [comment]
Hey there :wave:!
I'd like to work on this issue!

**Comment by sarthakkathpalia** [comment]
Is this issue still open? Would like to work on it. @LexiconCode

**Comment by LexiconCode** [comment]
This issue is complete and documentation is now in master branch!

See https://dictation-toolbox.github.io/Caster/#/Installation/Windows/Dragon_NaturallySpeaking
